---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: grafana-cloud
  namespace: common
spec:
  encryptedData:
    password: AgCrT7ks2sk8fRIXcM6F6ZJm14d3KO8L6LSX7qDVIP6fbRL5y4qBScF4NiIx32OWoQLBnXBelaH9TQZ6NAYulBjsttmpCCkMMPmcM2Y5wd+XCtLA4AbBIicUcFERkOxVKtCv04o7s5bEc4eC+/n8YgMYnIvF1sUVrkVb0yE6enQxGkellDvzlWgQJ0O2QLQrjG4M6SvttGT4cbh9Glh/4NcvNcg7QtXVymR0bSp9s+CpWvYahrMi2agYrKogCZ7TW28xCZUlXDpso0pMW6OjiDnwpIHThA5YvaSXUml/nFwr3OOUtjLwKfQ7KizVtcmjzGn5qU70ckt4xyAjHBLLU9rk5wxp3qFDqPDCuG2W4sdmDzzIrDMTrKSntF1xXIWQNPF4E0BuHe6e1DACUDo8xBpRSGR5b36TPxwibBFKO/7YYZJ+ngKYrjpf5k+KAOxbpxmYQ7E9gTEJq/OniTRUAO4gOdg2TICscOa0oBRGMju/RfhxL9rjmHWn9Ay6yucjuWXsYNBh8uVCgz85hsjpCnUnecoQoxjOuTrXAEDcTzqnEQ03n/eY2vDLatYg5bZnxn1KJawVb5T6g7R26DK1ouM8A8nqE/mGDwBOWRxZnMha49CRRmmjgEvxxp9gNI9VBfY1V140pDxAzRQRoqQASE7FzyzZY8lAm5IxEHXSny67/CMon/MyMg90GsSQQ6qlllh/ZJNWse7QSzRaWLsapDC8BW6I/o7oVx2UhPbmrHG6gjk92H4nQs/y7/TWTIeAfJJFZinGIOjnNF4SMa+jRX2hCoYfO5vbsWFjMWhjF6Fhe85ULJuMPjrWXegRsDVJbB2kFyVW0IywoozgRkTPm5GvGDJTNw==
    username: AgBhfz/XO7QCtl9+G39R58oOmOBxVuR5ag9GBCHMDnH/Kz69hbyvCz3wq9AFAqslaShQIIIAlBmJRWTnK9IPHoNx7qJXlQuekBMdT0jMECajmbGCPd/gtEtnJLer8djxFl/JrqQLSPfe0GMrDSdErpTLzZ+GL8uL7wLgHmpXp5sG96LvmXrfgyZGe8TwxFZ4w2ieMNdF2Pysy/zyAHS19HpzhRnaBvmNwWb3KjhY1M7MnvnVcI8ZPdbiQkKjKcrSjcRJXOjDiFq8xVbtOXpSXcO3EMK6W0/nqK9WII1ZY275VzMerdcOjdrgRzYYZPjhdhxoJ7FwB+CtYSkQSiaMitjgInlpw3Setycu6xCpA3ig3irwOar2x4uVYKwYmzJ1a1+rgDsVobmTMms2tyGwqbvcv+mValW2c96JaQwa/F0qFbjZJta3bbav3RIQPC1SpadBmMaUS92PsSwJRznQ5w8wdj3FBd5xQwzcqgvrkpe+PT78EsuyP02fjGfcjhiMS+g/7XywFt/NUsbDWj3d3vZqE7Fc87O/GUot3J+AwYz89lKGAG7cSGcGP6dd4xyB4VJrzMgMMxT32bhKiGnKPrAXG9FWGp8pavH+OxDHJ9/SmVWfdDqib7eEiqAF+RH8SzxKCxp3QMJiqjFqpUhnj7+1e0FIOnWkaoLDpg2J7bOCD5LUJD5yko5IkGntNpwVHTNOwkefiM4=
  template:
    metadata:
      name: grafana-cloud
      namespace: common
    type: Opaque
