---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: github-token
  namespace: flux-system
spec:
  encryptedData:
    token: AgClL1p8etYHC8bEKCz1mVPGsuB8TSAR4WT69ndSbGGEsPmdvXQ3s2/QXR8PVu3m4ITxtRyCjtMW8LRKtQnd6mudsjZevhtRDXLj8h7N3wiG0En732nT2T1LcsUNrJSOV8Hal7c7GgCBTPeBLtcmsvD4z5fg9C4IoC2NRzaBPhkd6zt2osnBKy2tXBc/So9/iqWR/L9eD/bifq/g6DjR6kCF7UyxkABtS4WPUyeKmO0Ep09mUMZAVvuUfYUIEwiNlzCYa9/4beLaBg1JuuHOoMhBTTtl5i04PXEcYOKhCSq7Sqiwkdk/qeVs28KzOj7HcCGZgHm9bRNWg3OH4xet1yg5haNCyTylg1JYsa7w9HBGPcm+bhlhS9Mn5nPI6Sib3UTXK/85ruJpcHcuZcmCN/nP89/o6jWx8X7QcgYoqJISvilztkgZGQfKzwd2g8QGhgjugwyZKXfvtv+ut/3/Xy2CGD7mxRATLyCYPorApOmSZBbGYPkdtOYhSKGr8Y9BuJfnWg1fu/LSRshW2fPsWWlmVIgzL3U1zI85aF9S2SLmDeSg/Ts72Hj4joT1N2OqTeW/chKZ0PwQR0DibFH2pfxBTL1FMJdBqfMf3WGphixDw3TGP76gVTbT747Ta0L4e9RNZmu9CnGBPbd3LpMBgO0NaBBihL4mflxVKfDiWuLbBHUB81PkKm6iKXdP66LMgqiq58NnoU5dZzWtaKNAKS+Q3Mov3qRNesBbjMzqTaG+zsmCkpzOaqqpdIaiQp04cJ83iphHeFb8K/DVJh6pY+a2hDhCBCKnU2O7W5jdYXW+Bbeg2QNptBwvByTJ5/Q=
  template:
    metadata:
      name: github-token
      namespace: flux-system
    type: Opaque
