---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: slack
  namespace: flux-system
spec:
  encryptedData:
    address: AgCj66ryWioA3ihabZD92bQoYviJnujSjYAvo3Umhe4Z06BaaDC6nT9WxUU8taTA05CmIdmByIKgM/lzZANAj0g9Oo93Vzxq67Xakm+MBQx83BCtxT8FRsg+LE3NxoCj1bctISGTkLFAZQdZYQQkdoGr4eW3FYN76wFMTEBEpoM5IEQ6GXWtdODvwAYT2iWd2owAuHlkTVM2yBNDk6eHRA2RWTgibNms7OUnHZQ6MUQSh0yCreqcgeC8S2yGDL8mSDhxXz9n6yFGHozBfRvtYo7vA/U2o03JuCJvkB3IMNENoIaFLLxmoEDWj4K36J4c1NRmZIpg6lra/HwSB0aQ+C8WloXKjBBe/emburu6bjQW7ZUOkDGQJEbSjZ2XGU7C+3wWyBitZtiJYtYvMrVBktUmTTE9m2KaYyF/CUce1bX3LFSEGIyRoBmpxUv83VqxSjqWaHPGMAU515ocjErpLRA7DVv0MTHnv+sC96fyqc8FIl5/pNX9NioytjH2rmykSJcOZwXz5Pz9RdXAD6xEhzrnQmoo7pCOjTOZQi8C+nIMwhmYMP7mEEAZD6kH+PIHo2qXuYOH94667I3kmdFLRy+w0iHhbOEUw1MYcITurg5VaYP0VxK2dlzOEg8BYx4idIwt4ZDolesv9ion31GzJ2JnqFLGo11ZRFeptS8dcNvMI0AIzkPbKLlueGDQy/t8H56b6HBapUP3c8/pyqoaFLXtfq/TS0nUKPClVuPcHpW2TEFID+EvaA==
    token: AgATav/tYbVtR2xejfb0CsFSIAOYdY8/XsVypzrzbtLLiLSCbTHPBE+0VtrijLcIJUREZNkfjGP6u2IJFLrz0JZtxzZvtD597GnFjMrbNveDHCw8LDADPZpkOsIl5u3LjF4T8kYOfBXncArszfSylmcuLdWpVOvTfU4LK/9nghEgWXgDK/7bbMucTycYVTZKbcr4726dwTg2AjHSfPB+SyAgTqfaTqSZ/vXxpS4QbfkyGgBUFSQOxdnL2o4rlk/SkxK93B/iamXfPPnR3COmcYkckiZVVzzudvmiq3oAFD6jptfXdKhXsORCA78xZg2YcAuy60Y1lLkdK9vG54OclL0k7zmIhlm/uSfa5qHVQfHxgz443OxpAAnnrsl5AstPIHKMcupV5Dup4/ZXylIhZ6jn1qwXcYDzB16FUuScY8dLKc4IhM+TBWRDBe3XxQKgiyjQJAhQqUvEM5BM2X0g8pYWguFB7sSy8BadfMCH3Ic8gFrmfJilTUdFeL8DKqCGixYnqSRLWVeC3sCHH9mILUeVjzTQXDH4B5MT91qMsBB8bOaBZxsO4soWXhe+3jznVUVI6L/aXaBmjxG83BdBWT66evnXngL0Z6Xur5tWWPW8j9lKTc15nqYE4ZvPTIMt3/M8JUIfGRCPnKlxS+itWSrQPIaJYxl9TLSRKmJXArc0cVALXUmu0MzUCS9WrpJzvoMSZc9CtHz4Y+WnlIH4m7Sd55CpUPzYannEER/4cLOpp6Vyh5SaBxxnietfEjpsjS1uGTdKZmvwNW0=
  template:
    metadata:
      name: slack
      namespace: flux-system
    type: Opaque
