---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: slack
  namespace: flux-system
spec:
  encryptedData:
    address: AgADEZe9rUvooNNQ7b4ndMCpyeiu4oXQTxRgFiOMGdsFdfcvgqSNldZIVoFUcL6TT5KH5cMpqltzSrQ1EqwgHZM82r7K/GKLnzKraUZRm9GCuC1Uu/2DfDyht5J73pfnJFvHKy6jbg729GDJ9XtE9AKNZntmBMwhzRHQPGIv8M1BzE1b9CWvGCp8sDekr0ZGxYrIPr1FkKs3bNBEgMA+J4QXTZBgTkLMkX+g5g/0YvL0iR18KwnLjR85UXTPoVGrui90HWS82C97jgD3dh5Duilf5j8MEEkcvM84UOnnanHoZEdQDikORCk0LOnljxpN+pTzzms6cHSg8RSTu/cToXJTbKIk56WVf4QbDOIh8pgTW6fgFqY4JtyqdyUVS2zN3BPahtUyzKd1HXvCDtnh9VSbyLgZvUqtp4aDpqKB1n+CL8k57KG24imXnLZpvWGZekwhgAYECq5lww4+4jdSEdoaU/6ggWSxQgvkPWPAs7baaXzwZotzqS2shhV96ze9+8DAR1JTpSDO9MyAmZnihAWor7vEzkzOjXcLPijZmgloqddZEY+CRwdRflsgOcDcUbUz1onQ70xIPhyITmehmYCsIxPBb9vRbMumURIYfF0c5DRcuYbRhi1FbxK7cIDSzRN2K7e65jhE1sscDT+8lKyLGjyJbq9Hzeo2F9HjnfTwR12yBQJaQlhknSA3kD84jhELcGFnZzd3Kv7ge/zPdQ6T/SPbG4RuughiDEcq+W/lUXEB/SnMkQ==
    token: AgBiUwPGqCcwsACnv9uplMf1u1/vkmP+CpMPXlmG3UVfwqL/+KuZRxtynHFeYEgjMt/d+4SMM3Fg5ZZrmXdqNzQdIdLRvrNCtZBLuWsCBmWLoSzWdGqpG/wdBpzwxkztQsmKnKSg63TSnNjA14sWrR/4Dohzatco5rBCeygm3c40SSJdpX6rKM2FmxRw5NhhRz9n6mPUbW/9D38FB2kxTDO0JLiVAm0XJHdq6QW7ggr4coivRcXpw3hFYCvcJTZ8ct9G6YyvFk4ThnNHZkG7gM/aSZiBK3FAQpOlEetODgZnAfC3MKxGtx1x3Bp/xZF7OBE7X/zgGuRb5g+X8qvFjRTfm/7QctwucSOMxyZJGO6huFtRvsVEFg65M+pCE3cIzAE4rr03rnTmd+82PnhOpPE6pW4+EQJdkseF4DBd5rHA0VRHSzWG6PQtupbiI/U122qYo7nd/AvQU+ZKViL9gcm/YVL61DBgTFrdvU7yqAp42h96FYQQAb/81ATPP4xSMzOISnbs10qxRXYj1f/iUFEk20+vZyEJiSBVIXRn9ZqAsJztiiOff1v1N/bmnufD+5GrDpEIF02EgN8Pt+0yMg1FAmrno7iIq4A/mQy3MZXzzq7BheUgnd6Ao9tlLxuzeYIMMvtaGry5rjRbGOu23Dd7uGeuxkDy/yIQBuAFOPkPvmI7hc+PMXLNyXqVm8seLeZkGqqTToFv7e8FVjk2GG4Ros/xQk1tBKIKnCNdy66bOkkDGBl6qvFfIs6aHQiJhQiN9eA5KvfZiyg=
  template:
    metadata:
      name: slack
      namespace: flux-system
    type: Opaque
