---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: github-token
  namespace: flux-system
spec:
  encryptedData:
    token: AgBFHP1qKnjDRTFiCnH04Gju6l8wk/KjBWRVHhy9NKZzA8wRWbMujCG0wzJpjfXbnjZD2OZrpKHJXJRYrTLGyen/GxhsPCR649jiGMXyBtY0JWHimVuHPNZyY0GBLH9N+ggXzklPaZr//0JghFsJUaRiy8UdLiDHirRmoSW+qX92WE7fns5EYlCYW7MEyIe3yvCpiBYPY1Oy9E/RlWW2meIAMJX0ksuFRTGuRq7UiZIsaHWHHI1yqMuvO10Z/F2L5PsAcY94uqMqRcwdAr/kW4/NXFBPNEkincgohSWyZSb+sWwO8M2mTkqzh7/v7NSXitzrUL7ZMH7Xzod+vNg4zTVIVmKkWjj8BPnYcL0uqk23FRfBJOhwYm2icj62owjR7byjjAjzBgEaH2sqkVpcb0OT+Q9RqVaTUWCh2xUuY6ckG5nVkTxzXESMdvBrnAgSCiyblEdpK38QulouBC6j74BSwADtg8e4waRq/s+bluflaVCSJ74iqbW7hCZYBko3mggegqTAxpVxtea0Aa4z7mfNLtZ2j5SvSMIjJ/JbDFqdtFBF+mgoqX23NApZ/1GHvwmtKjJedyk14gZvAigprStuwxDQbDyhCADIfF0K0RxdUZV68prtJqs1s1g5bm8XsMVsnpVSYSILXcqWsVWmdh1DwGrXrPkNPxzy/QuDM63TjPkTALrIrsTyOJL/7VHOsF6WJjb6JvqqEIT54CzjtC+UPEl9keRHTa/H4p1uvU7iGtwjC3U+jq6oRHNeqvAvZM6kq2F6hP2zWnHf9EObgiGV/kfMBpk5xT/z/YCox2OyCwHiKa4ub24hsrKDKCc=
  template:
    metadata:
      name: github-token
      namespace: flux-system
    type: Opaque
