---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: github-token
  namespace: flux-system
spec:
  encryptedData:
    token: AgCF2sbocMJ45UUKGVvvcDb3MeqNZ0ZbyPpkC66c2GCMLePWJdMv8uBpX5HNfVamuisiZIp/F4+iCZZyy/6P3MhMRb2nf8PHQUrCl7pYISg8wFKWirzNN7nRQjwnD3Qooo/EdjQgSLRMbT3hrqQjJmTNxKdsjZoeaj4ZzPgqZlCQeRGpFxOf9DXMVJ6DT+lOjElEyQSPrOzlSiHdm1fMfIqQGv1KRUHRMBGuKWYHuGM+T4EGww0TrzPtryl75euNOvICMOw4QLcaGMsxcMsSNcqehGEy/eAhQ2Of40KCtYZG9TQkaDmNvbH4zyOzPsX5i9B/ht8TrmeQJSCZ5QLzVWLFlB3qj95AX8APnAASSEpRApt00xjgny/ZGKUBtvp+kRRrJFfLW+oAmGMDxb0P96nXU+Id/aG/X58I4hPxUxANYyBKH6T1fq5ygjuoifpe/IRSzyS1zrU/i8XpjWE1nrSJn+0BG0J1iWRQRmvrbaNv5ppmAC9aDjK4lZny3/1IkED/jQZlzXAGH1a9K6vS056mxniTiSFQUkFykagL5crbz8nUTdI7iZ92X8Pwcos6X9ygHiw4fntL8Wbf2YAcGgQcYq+wzhelNcQ6/rUEtqMVU4Apwz+CAiR4ICUP7WrvnvG1f/wge597V1ZYhyMZFfXu9QT1pOmJSOmk089qlmMx8ys4UEqmO6M1p7RaI96cCpYmm6V87wUirQ9ShK2yH4pbhq+HJBqMwSTizwUgmrGFcCUeHolqVOnGkEL3b9BPBT6WCnQW9B+CtXqQgkLKXe1nY2eyE1uLgKfjcddkCFTJ1V7Ztxzqb3LFl5/Bg00=
  template:
    metadata:
      name: github-token
      namespace: flux-system
    type: Opaque
