---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: slack
  namespace: flux-system
spec:
  encryptedData:
    address: AgBm64viktY5jOqb5AkyWIS/DNuTXdMTTdxjD6IGc3EjbvGr5AMoS/QKf8bVweXj0XcfX3GbcPghJJ89QC4dHFCMwjF8fpb/gFnC/K7LhXj+xKQhUlGWLPV3UeKKqM0TCCaXJKxqpX/mRVBjrGH4sb2mXaW2KOb9Er5pHJYhQ0xMp31R9Y+eVGf2R5qeu9L2LUJapwVCQQPSbGy4/PQRNiW8/wrdBvdOVq+GE/1ABTo2kJFvbzDv5wOR4ONCJj/5H/OZ7LtnIpOJXErgIAlj3YCT61z5Wxqa5su4Kmtkq5lsCclYnoD5ZcW9OK+vj4oNLHjsTAk6ByiwmbsOB1ki48/VhaImvz0nZ5dclChLUXmEiQbuyJP9W5SlI9Mn6tUHall6ahqo1MHbxq+lvSnVOOm05PkmfAYgzEl+4XL3PQG0nEJ+OUwAMi7l3WUKU9YdqB2VqNNpC76THk5PvOUariWKWTLlG7HYxohGrPDKXI6zyF2Bu3f16jli7VG+5DB4dJWWOFXFDyTiny0R4CkuvVmJ6/qJjZu/Ppsm18REgp6+ZoWquoPZHDcdaTsJF/H4++yXcvKOeUkH7FbEJM8SHRdSvenHW7xCc12TD+fnChkWcDkVDLnUmQEhHXz6/q+2Zda2MDllgRBZLdZnVcSIS0al0mr+pfqLeVwtlDfgLSNSn6dvjDCeVmEVJXroKiTdZoU0FakWFCgvz9RrvJ9GiwDJUJZn1zON/B4+ll0BoHJNYbomK0byJg==
    token: AgAIak8PiaY4fr8xASmG4W5CmUqdBYWYwJCML62Xb40yDkdqp10HlyWg6XrW/cVxVcATZMyhSrrhYK2kShGZL9OU9dzxfKKnXphYMVks8+t00C24ZqiTSPMt4tk7BDnI0RUcr4/SW2W1YnGMD1vkRHht/ak39g2JUNLNEZDboAUmuKo/3r1mUUixNOVucwx8sfOpU5J9LaKtY9UAnvyf2Cv5Yu4riBqVFkNDTQ9rzjdrZF1ar/70umGQ8eufXzPmNmRSqDci0ByQ0dGinhzQVu/AyzXVYlxpOtObYWzQ8gJ8xCRTotpY6SRWVQr70TfkkgtUfeUVHpta10Uukbv8RDoj+0GjjwLzKNXAYu7QHXqoBpw+4dxNd+ltIqTEBt52wc10H/favwAvxhgyXQtbS432UQpZ3Yho5T2Q/RUvaMno64WPc7+t93LB5Jf2XRCKhhUUJIAjYppDwnJzU8eM7GGodcIU2UTEc6kLzdX1a6y0lxIv3zKuXMFW7wlcaoSJaYHZ8ja3fJTcoIbcux+lxha28KGhQq+sBhbczrEDZlZ3WHIVHl4t87OZ3WAp11EddlLPDkydmk37Yhy0nQ931mDooQsBy0VpVb2XwBJvgmgukBADgsUVpdr5furn5kkYYsfPsqJpM6cHhF7ZPceVMpNiey+4LEje1vjeDysOCFBA25IMZ47iD8Wxp3eL7iyQHKdqCSuSzVEdlic1SvG6JLcb7+QPs3aoQ9j3e6WVz4w2EcOlgMMDwcQWQKGiLZMqsHEIGr2/WRUYwuQ=
  template:
    metadata:
      name: slack
      namespace: flux-system
    type: Opaque
