---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: slack
  namespace: flux-system
spec:
  encryptedData:
    address: AgBmirE3RJmzZULHU2OtcGJE1kOQtE8sRU/yR8vcn5NykC7W0JaDDXe9Qou96lO7v7oRB3h1DHWfmpFaEk2QAlMQTAEyi5olWjals7ZeHykmte3nHmeTCPvzv/nLKMg3Dj+rk3hq+Y+xV9Ccx/SZfKAUY4d7D1csC5gk0h3UFIqHWMs6aR5Sy11DnRjb+4KV/O5wPJn/60BHQfw6z/YL7akMHhXPdNFt+9RcBMoF1hdlVKHHUnKhDwgRHShCVuLL/oKzmtBMVXgj8S1/1YT4+NbpuF1lu3T27tCBlAEEO1UGUjuF7uBpvwiIYlTHRk4FSTsWYPlS/VXMqwoc593N+mfByXiIGZNVrCBqF1SiP2PjU78MrIZyPWh3sGtWZhP2hhAUIP0RVSOcXyAynLXuOvv6mkp52Pk+lwwg4Bi+3guh4MdEg9zvcBFFg2NNrLoxxd+Hdx203yNyVNDiOqQSezbdCdedk3/IMz3Z9O9zsMrcVENJLHdNJ62sLj8OGNfRz5wsojsBcWVD7OIPbeEBiLFhhFApIOxRkDkunQCMmnAP7WuExe5TduveiP8i8sfp+S4wYqAc5EshphPlwdYgEOtl2/DaSl4WfOVId65RTf2nTraNKZtCPqYiOTMh1LF8gJpy61uXbgHk6mDwfGqdyJkiAlfcahXnpiEdBc5rmoS/EyFvptstslTkvE5bNOwbBYok1vrwsjaeItrfXwE1gwuAg5jJULBfbl0NiT5f8Y6iX/j3kDUqtg==
    token: AgCVuVI4hHFhccAs6Y0CTxQ8vdkin7r9l8vyXhOWpLh5iteA0eUkMmfzoy7wiuMkaZsEQuQfOwTmyRnAqnjJ+1LWZ+vYOR0lJjbphbMjIrJhBjAWIdCQr7VTNtQBHQYrxiB02CJDSMDQdBQKHU8DUBr4WAaRnqHKXdsDimQ0h3fSK4Xk4nQoviguWr42XS6U6mX9nt8dq62Uv126qi3CzIPpObhaRWChWobrs18hWvvHpeeHtCqV1ifxSWZFV/93ofv8Du0fDslULewCSP3H9+0Ake6N5sHerIB7OCVk99GMgTEpo0/4P9Y+GHA8kfpLIelkUyd7tlrz79Z1M46n7MRbJk47u06/a1KPE5OKvvhaZYHNpbDLvH5bkPWbTUZGqFumEO3FOXV6Wx0CsKAG3PNHLNs22rtr4P5jFRLM9pkNx7eLhusgKtpXZVXdlUQ6k9tNVbDmjhsHRO94x7bE+YQusM13vFjMaZMR23zW5p9v+fff/5gPkLQDu00U6JgOHjU8ZHXwooTi5IdY4o1P/fkt0iSSxN9S/baXb9l27fCIoeEz8neCssgqzs4HfWoBgQcWm8R1+jzbl5gEqwEGiryvJflkGGlR9YB6eXVf2iyQPLC6DvoOqRqpzRxk4UDajLCayI1DIDrzGRzFNVDXR9hIUO11uaxlDOIgIbmhhNSSsuXXSUkEGqdwXCuM8ZQHHVS6Dl6icTPu8Cubrps+sDVYLVpHYsQu/zfi5MCceHIo9y4m76Q4bhSi/d4QzyrB3tGDj7zX6eByLBk=
  template:
    metadata:
      name: slack
      namespace: flux-system
    type: Opaque
