apiVersion: notification.toolkit.fluxcd.io/v1beta3
kind: Alert
metadata:
  name: slack
  namespace: flux-system
spec:
  eventMetadata:
    summary: "staging-lg cluster"
  eventSeverity: info
  eventSources:
    - kind: HelmRelease
      name: '*'
      namespace: common
    - kind: HelmRelease
      name: '*'
      namespace: staging-lg
    - kind: Kustomization
      name: '*'
      namespace: flux-system
  providerRef:
    name: slack

