---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: github-token
  namespace: flux-system
spec:
  encryptedData:
    token: AgAgWqP67wGwc6pWPbKonWxbGBPHpQHLt3a/tUIeKMf9TwkQjLSZm0rDPrZf3A3zy8u4TXuURP3/PiWoYVVk/9BYVuxvaez/jipDMH+kY2VJJt12A+dox+cWBVdxq8NxbLuTnWhMFARhWqlEqssBONDSaLGUGdcg+NH63s5LlvN5olFRyxIbPAHtY02ZXghPh8mKaArwMt9Eb28ZAJbH6iTjL/r2DprhQs9V9t0x/cO4spmp0374Viy936zMZWgrMv2Z4NPtvE+lx9PvxkGF6x1fsbuTA++s1vplv9UhTNYu9Tn0RiclgkHLH7fzLpj0+N9zvzFH+hSAUVR+BXMvauSEFNFmJdDYz7meUhdDJYmrNyqUAvygaF65cAwUboOq86zp7hxMiBMVWfFTUS9IpmcEL6/54DoYw/39/tMvguOXKahdFBUfzbJkX759pDo74gQdNWgPCLGeXktF4p25htDl8vzKx2O1HvzqMqDPexhlSQT9mDUkvzJ+YLTZDLsk+UaPsud0RRqn3lueJCbfta4wy/kRNeHof3ONeGEHMDIS1+PM7UwW906mcBqjR3spHK3BRHO25dj0qRkdo2AF1kJlaj2zei/INMpSCK1gyWSmfTKvi0yTQm4DfajnQuFI1PnG7y3sUBoKiMZPFe0ZYJch5yqFzVXgpDkCMOuyDZG8FX6tc0ICEXo/752Np3RDIQJ7zFC93Bnr714vUZIOlBeM0tN5TMx5xzOKzlUibYfat+79CfXVAwzYOoGJLKeRrVrHaDSBEvZKo9NEJVfPKqk7M2iIySoax+ShkMXc9SFIeUeVuoX7MxXaE3qa1lk=
  template:
    metadata:
      name: github-token
      namespace: flux-system
    type: Opaque
