---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: github-token
  namespace: flux-system
spec:
  encryptedData:
    token: AgBmy3MG6sujmPN15EVTe3/DexxQbqPIIjtSJyGGng6DmmKYJnmplMUF40a9CLdrEMOX9dhhGGaY3DRXbx+g8nK7jXnjE6SARUnS0RRPNRVVGyVcY7ZFEQ7iMkh9oAJ19tWtYzGl0ezOZV8Aq1+nLq6XgODQUorrb/QDIjVIWMBd9r02Gn11YAlXfhVFs3mBCOdxIkQVqXW+0eNsJqyWt8PfWbvymLnz4utoQYpnrBaVyHMmHl+adHPFBptaGYLyWHRZN4OuzRk4/CAEP5kErrC48lQqzl3PpKpEZiLmXFJGk1I3IUjWDS+QzKvwGpOJm2TuEd19XeB/EOQzPnksWktXN3YUdk31LDTpo6OjaHliI2FUee63oOMHlmgpbVZwCfxBe2R+7ZM/lo/OyjzDidtQEaxuPgj2d/swMNXhK6HkpK3DOKKJMz1oeSK6JJZfwtBaWPUK9sTICXDdfgvk70o/P4f18bc0mamQDChe9NafwJUJS3tn9AkDZHabOjXLrpp7TlkF5BZH/CYDeyJYiHerzU7e6/CbUCPuRSzzPpmV75WPf5CWKA3ISVvUmQU+0NcMaXEQZkF0w6EeYY3qebWj+xXZhv2T3Vf51UTHyobtSiX1q1oKtDJkK2ShNtzaoahgzS5SaJUqj4H9ZZ/4ijdM6oPq3itd7sr7i82WptNh7gdvSqIbXcuhdqreK8Nw9d1mE20fDvu+fLkz1eRZYP9Q0XzANrXxcYLS/b/B1o63DE2IKgo6x+c5uN2OKU4EUBuhuVg8h0m4vuHo1x0h9i8T+EfYgZC4aEEGfoDavJjlTdDqGcA5zbTzVR1rTbc=
  template:
    metadata:
      name: github-token
      namespace: flux-system
    type: Opaque
