---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: slack
  namespace: flux-system
spec:
  encryptedData:
    address: AgCMgNikiaz9hp06/iOSHpZTUpszsSxVRjIcCc4uJXgUlHB0H8sa6MhAr5Qth46EEJFvhr0UnN7WcvxXV525GMiuGo74kjItMoOlUnZVA3wsVBAPVpgru/Lf2SM3A5x7OJfq2NMVmzPY5vviYW9ZvkFwlYjSw5az2gMeZb1uSAVPfwy/2oD8kEAQtSoYF4Ammx4x6MPOfo4AYRCKzW+VAEbml1v+Vs1g+R1qZ9s/MrjDpPBX6HQMJ8j1WTo3XhAXzPEl8GrSgRb903xXWHw2FBJJDhnxW79XGqJtrEmub3bJ5aeXS/vF05YUa7xzPmvKkQtXupsJQbUQyG32NNBnTdesLOhxkyfdl9rzndL+JehHzZo8ihGszJVs5Kw91JR4pP+xrCrqbkKRIoMkPeCoE4IAUzXsAXubHOy8yv7nF6L0xps1WJ5zM88VULm/Zk0xkjIE+bagfMqf+uLyon2BdYxZYs9HZ4ztpFsaskUV2waqwyV2x4kaWsfiZxXanW/cHaGvTmpxFW0fKKCbHu0hvaZJBgzIEuW2zZv/HtOWuPqMJhYcs4r1f2UmEpgsXDohjTY8tBDjDqGgJuGW6gSFhuhzX2yaE9IcG2DbxhwinCxSUmo2gOBAkGEyvtCqcExPKCE++p2tdc4KqPrfp6HAUrdeEJSOPTFVA+UkGOQJxnZ+OOoX2v90J5Lf5lFgqozm3yrCzF5iveNDgm0BHMv83Gwcekjs3yqQyhTpx2nKvL8LOivF6cCW9Q==
    token: AgAd+9PTR2/1qaIOZq9Zq+l9HKWkWS0SygGfIYsT+Pygb1p1nyZAdjVSctAPYzeSHC5mFn04dh/s4YFsVt7F+eqKIzn6Sy8UTKvma7kUnv3ho8FCrIgFLFMm11srbMncUItB21z0jB671VyIf8aiEy+Bua3TxVuec4FVhQV0SXLkWGNfnPwA9e21J39dX55SPXxu2zPH7nVS+LZcOmlrnPmiN7pTK9WiN2KqJnGgHi2WqeydqSAr/A7Y9BQ2fvKN0bdIDZifpyUjByUKk+f8cyQR2QVc0WU+JcBaXhbETapgIj1amI8DTmHG85Y8JhlDBvkvxrjGzh/Iu472FIIBWU9Oq/uLD4JEIc8Lme8TGdQPRlzSxToSLfKHYaXLN+tWAT7l36iyHZ8Xxbi2XmdQv0jvxjqx+VY7W1p7tDWx0WouHwQBbnWKQvraH/29OZzOWebGkrZpbouh4RjaA3/YevGPUU2vXiAJ4YKVp+hI6jL5/goiMkjLZiKXCt0qbywLiFsgdgGF50NT+Vgg0j6Oo3wQq3Qc26enuLitwYXiI5CZHfeI2xXdT1mYqgHMOveWZE8gwyViuqzJoUoL1tr/jF0UqO6Mtynmbotgv7HHTUrotx0U3b/TzQr7LfwvHPEQcOCzvJuJLWCaBmQVtceGInNXdeq28dDzgQ5WFluqdLyUphmdJ8OHcymlw/P3G1aCu1qY1u0OhiR8uXacdoJV1/1UOJ37Zpp2CP9dJW5MvoNdyGfYfVNFukEETdl0OiFMHcCW75AVpWD1XbA=
  template:
    metadata:
      name: slack
      namespace: flux-system
    type: Opaque
