---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: slack
  namespace: flux-system
spec:
  encryptedData:
    address: AgBX9voEVLzymQ0nT+b9VbcMP3kvLF8URWgld8qBvVzbSfGoYY5yZY30xmoM6Qlzon70sPYbaYdoWNBzAP2J6YBOZeVHfByWak/Ou3cmFyQEDxjKaNKHsnEcTCa9JDOnFZ+z92AaPL5nlozRO07Kxp1qAJuUK9fsGUKGNmyFTKJLhOUo1yWawBR/BpTUhYj3yjeglw9A1gnYfffhSLAwWVXwONJc3R7WKtNDJ4rcsJt8iJxySjgDVoJ1y/fvI1yFgO8fB2/Y18HA2iiE3SrD1+ZWEhVLnv923o2Eu4P4Aj6KNANPXoD45vB0tlwgqwwQTTK8f9KZxKQUUY1ZGe2hV1CQyteVJ54wIYCX0GsASle/un0S2+V/C92hinbHEf/Irf876KsdhfXSm2U4VizWTCdzoeVSzEA+uC/JhwzihfRwQIXrXMxnu1S99ze6q4tGkNW29Ip02KwVLSYg1s5ZCbk+gi01f6e6iKCT0WScEuk6iqJsbaffkZjioWmQ4CLmg8tpOCa/YfugJj2x2qyNbpcHT/0ZPxD3yDxG28DX6im4eRsmCqfdHimKXYw8KAC4tt9zTKbBfNgZyOE2r/kWHUzwsG7nuphyymsML7Foxkn5SqKJx2s4zL4+H0qe5GC78KmDNtBBz45GI8WBzowstxyGLajua4AZSadwwTXM+9d1DQLKGNLZ9EnMndCX/ls3jLGd2RByHM3hFmyQHlplVPLVJsCovCutGWYBwHPdieHCE50nZiL6aA==
    token: AgCI/iB2Z8J2CriNNQULlvGP0K8M/ANwuzM6RLrTdzGqdkIze5OHsS3NSG7MFghqeSfYcY4IVvFmC0K44gfe7gZC6jJZiMEdK1VrCKDKtiR1CivaVbXjbmDv5eHVixHK9Xc54e/ySQuY3EKih4vtPmoJeh9l5l3/O2fDfKaYHKm87ubMjaui1Lm9u8nm6RuBvXm/Qsr+a3Os/DElwAYpydWkhiR2cTTf9IDibeKIaE+/iEGC2LsMGBSHZO+mz/Pa5mMhp1nsMKWhLDbO6FxU4Zjb/I9hSkNLNWBaqDdP2Wkg01iVHxjfwRNVOjHBfa/HoxdeVG7zScEcVtyhTaKl31Pqq11qadK109DOeSpZdW8aFPJh73+Yc6DWG/fO/003uwlcCQDeJlyyqIux0823gLvLNv8R33a0iGqUgrO28pxzhmDGbCjYNOYiIynrdVjc/W4qs8ZJwjpGm9v+3z91dOnnRsGNf5JmqQOiCfPRmLo/nOrqpQKDsGQxDMpe5kpQGwzAIk1AwxNXe/xvnOEA8fvyPwGnJjqvJfVuyd9vcZ5G00YMPrvu8ENwLQ6TkdP9rsP23dTEEFzix82k7PdA5gMVfGghkyWDyPiWYrsJoJf+PW0nMvGnprcOvyiaL/INfa6LFyVYa9NFwsuOBiK0DzVMskmcfaWrHy2Hf+lu8YJAsuOMU9bPIOLTE8jh/ZBsoqBpVbjXfhVR+FMpXkB0COX3U5Xg9OBOs70u29cOdeBSapj4xCU5PWtUhZAQLFxrNT+WBRARjDuK8PY=
  template:
    metadata:
      creationTimestamp: null
      name: slack
      namespace: flux-system
    type: Opaque
