---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: github-token
  namespace: flux-system
spec:
  encryptedData:
    token: AgAIcLwM1Xd+ljr7O8zDzZxQdloSnqhXoYliJaK06ZXLZKQfxkqP59DyurKOzwtKq04KMG0QJgq42MmTgk4WRUoO7PT29syHRSggb4zHzH8ZL4OxGhW8eHSBaB7iWyFuJBurN/8GKosueVP8jJakcrRVbEPpDTiLFYfd0tdBGVnGHn/JwLLLheL77QNeE74P8XGOMsxLskDjJA06nKTjHo1G8qS2rE42L52qExjl9WQ0/I/s1qXcA8pKfL9flmpThHyBf2slgUVcFIYrPPZHMcBadwwL1iF/vq2nyEIQ4lz6/ZI7F9RijDTm3ox7Jo9vkMGem9ocKOzJHoxaai8uc+TrxfhhfktKTbbiLhhrEFNiNzulmYEWZHD8zYm79IJnmY9XzpNbQKT2OWbpIK45cqi7VPkMw2Q8jiklLautk3t7gh49QlVWBiQH6bFUl0GGwFiZ3BifS6m6xzh9tcNQsfLJhjF0uHXPij3UTXuJH7hmo3oI24rzWpHW10yrNy1qKKvhjj7BTjaNyBQUuXOb23rfZBmSwyY2XCk7aqFEHeFyHa2L64hYan6RQ7LPnUSpHhg01R8dvB20UwXzBVrunbMAhGonH2NzQST+mK3kER6IpbyXP0pssUHLzPYBdmFd6X4Y77ZYRZjLdo6acNR3hXcy+t2g1tmffSB8lKG+tHmqmZDPKakq9uoiB+1KWdozh37SCBqwhUN0fncCRz94k9QeTEH8IhDOh0NFYDN0RZAPpnMPiWAwvEjtbWcRNFKYqh4YU6we4Bz9BI/66dFPXu9LxcCjrCv/eUn1fKAVDpFXSNR/vcy7SGkpMTTNx1Q=
  template:
    metadata:
      name: github-token
      namespace: flux-system
    type: Opaque
