---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: grafana-cloud
  namespace: common
spec:
  encryptedData:
    password: AgCM+uSa/qAvguFQI/f4MY41OZe5lJqsuxD+QR6Ksm1xWCPME2cpAHDG++dW7ncTftIsZGe/2FjgcsKTpMey6tm3QUzZqf4ToZHPQxucTfS6eO5oDLLSpjgS1W0wtv6ge0F98XfFRt3g0EPVhAHBwA+GKl2idjtVS0vrtc4UR/BzbWWxExVtDY0ni4tiDFI0NdxKpmE3UmsnmrdIOIw22BPsPQawjY8wKy/XLBYInCqZWMPL4/oPRL2IV9rZ/K8YqwcjozVwdR7MsqKXEl4bEYZFatOaLD844bZLKcw7ZF32JbIbwK2oGjVo5v7SpiDysONdSA2XkdQsPl6E8OeXgHGofG1aH1XiadQFs6DHxBaBD8LO8vr2U0uHDcLR4zyJBFfzYDkalpx9pmfhEvBgOoHdMWcImSAUdBbH16HjsalJEWoGKq1H5aJktAC8Q86RmkOG7+W8RlO1qHSGGCjwyKpe86lNw7IxYOOFfXYE6elvGJuqo1VBMQUlAIAtFn1X1VUxXd+Boe6Vrdpy2Ptm9XmcXWIZsoH5jM7oHuWUK4D4+s+R9NQj++tksWMwuxJnXkPTeJr92FkASD751kz0XWYtpUjBwjJzgULbF+zXWBgg09Id+WpFZqmxfNP/JecLLkFhIJm/YWB39uHwzWsdSCzLL0rE48f7MOgMlEeVHwM7FnfJqeszTpoZq/Cevz8LEm4usCd8O/kX75ObGowWeJ29vwqRpZ9PTf922+PrQKbXlF0pPsQhWahU+IZnRTH9eZUxluIHXtNDDQuQFJk/8E+YV+7khwrTXiFjJnptDsmaMoBuVcB/kZ27mxmSW7UVkjXSxziPFqT1lBjfloobgXSJpzwNoA==
    username: AgAFXU1Z7cPdHZ0sNMD1VChmGQIwzw+MAUTzktDPdBy0TByvtF37REsicDuYHhwR05qYJRsbdilNR/LkkJZrDemwPmIrJbR15hWxC7DgOKE1M1eU30KEoEFYwXnXaw+/LXqdEryjWEDWPmueTBPWo5UbtJnwXXLD+8vI1SCiBGf/LF1X+GARgpgLuGIbnY8Mrd2GnJsk0i81vmHJyEv7mIFdsKUDPfoQ0w1mfO6Rrm72/WqLcy1rHPWKQInNHoGkorpzX2ljBgeOAoNtHAPOWxzzPusdPvlgZFhmQoKqEyKA0BeqcspH/fYg0/NbdFZ75+YKMIQr3bX9SAcL+/Le1j+gyqo4lCSEM4rcBYQrxxLz+G3er2UvDdhZXTIDpYLkryNgOhnjkOesvBB/NN4k/k3iiPVrTx94u8lg5+nmVEyYpimDllZVzLMj9cZsrtiLvZAgBmKDalLi6KHrlYAMHadpAliZhViP3R7K22SpvywDAJaYr3oAM/vOn6Po5K8MiJwf+gFF0MhqlN62F/TTdWjV51+Uvuyj/YvTvrxUCHv1NedPrSJouMj/xeRW7jf93QgmNppnfxQfbmFdCSDw9HrFWobi2CPpVoNjc2JMnTSPIsfcfCrxD+4AOrgzrWUQZN+o47eAYjJOxgFeuSr6Z15wedKHRSasFHZTLUiGQtQzsvokTIVBaCTIcOsgcvwPdvMkrH0zd8E=
  template:
    metadata:
      name: grafana-cloud
      namespace: common
    type: Opaque
