---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: grafana-cloud
  namespace: common
spec:
  encryptedData:
    password: AgBfDe5kcLVJA6MdfUETkYjaLZcZ9bAYlhVcDW98y5wQnNke5j6Hsc8TmLEprROtNLZpi7YlqKkrC66gJGO4CffwK0NoGJjKPIsKhmMiivAIiPyvc5yFEqjCl14v4eMFEhXM1//nmkJoU0Vg0niicZg3D5UMBS8udCbYxz16/j6f72g+LJETD+fjzIW91/91+QI8WRL8fBoWGaKdDAD8HmrCjdUjwp7ViKgM5lQkOAwkA+Km09+GrjJGVcFO8ckYcxozjlwsQAWYxp1wzXcw+tN3wVAQKVuY3njBybw+8/PeNuca9g9oU1rgsGHwH/oQGJYINlKBl3Uod/dfuQQ6lZiSKjxbi3dARU+y5wvQ5kTglhASrTIG1HVZ9S3+BnOyxrHYrMEqinqffS1qPnasJvgzvpZjlb5gFOzrH5DfoNh3HxYC06MXDJTaXfnh1VkmaO0iLcFihQSenYE+d8TtUE3i4+AX9IHmJPZgbiZ0wh5cjIRyI/Fkv6F2XPFS4pT3PIsF4lH758yDBmuhhQTDIyzsRHsBMHJhKnk0EvCLWd5JhjRDDuAeb2mA/7PgBBK7Nu/ymY7fCoaCdN9CF2WvQvKU3fcB1V1hyd8gNted89sur2dlekoYFaHRBNeNQAhvrd9koceDoq7/JFi60e9YHXVvPFyqgPtWfgVPGvtafLlm/c+DNfJlnq2P1CMfNjHwg7qs9R/FQlsiNE+a/cErX8b5CsUdkr2mms2YnDccRrTE+4IuuOYHviKSfNn6WyXMZHEb7KcCiCAmqqNp7tDvxzR6ww4jS+oWyUROxaAuABWC/uI8ufwVfJG7KjKnAXqPauhe/AczLoV6JvRo4NAeRwrJzkQigQ==
    username: AgCJz7CoIFRo1OM8j8An3MwtGiFA98+w5aGKC8c91/WGUSBGQ5gou/cEVRbmroAg6GWYaQ02iE33gxaxB1YVzQfG0yy+zUJSJR6f9g4hGIUpYLPA3www2Ty9I+0ligYX6nN3lwvD1ygr0JsEwlKpNbx1jNJtBCw5dLOYRpYgUM7fJfc2i+Avy8MClG0uFnjUs6BjVDnBmifzd4YwKbojaznLCerwxMHc5Efbm961Eukn3i4RYA3xkMphXcJnvZBC+ToQXSMroUmPKdFQJbKObTTrQp52oFjlT7sPs4DzgOU6rXlKkccO+tULNW9jB1zu0MbJvKwgS7VSwRT5UbbK8xUVyqs2k/Gmqkj+HN2Ub7T+EUwc8lwgkS+69D4ihVUL3gkSXBLlNTsWdcvXSD/QLGbLxlmGSNVXjl0ag1Zd3BqF2EgCvF13jxUPDKLRokhszB8npibvCMvUkMK98ElIbssQGaIzUWq6mszCTSMUVrH6Eszr+efAhktu3u5YfQ/oKyVar7B6GS+86o9Od+vCFgPaUYa/BYis/FwLrY/Cfw4tzPGs6Vaf7fYQpva85QnlnwFzJOVYvZc8jmxoXThAfmuY8q6deiDPaKdMtPAgzXbQ91C/xXQZDZZdco7skL36si6UaV4KIEHrIM/DD3i7dXJ9ORjsPe14fziU0GFzSIOVfh7t2a37psnwU09HfLK0mvHedwWPsTg=
  template:
    metadata:
      name: grafana-cloud
      namespace: common
    type: Opaque
