---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: grafana-cloud
  namespace: common
spec:
  encryptedData:
    password: AgCIgaqibsyvzD6U/HNLKVt7nU6Wjg4ATSC3tS73RUe065UK0hEsRVXGlphqWXDK9IZAtSL3EckueEFjy4guF1mgUl/MlTOYVXeZEyNlVtElazv4F1XGXKAhqwuHurDBhxEgJwiArY7eVBsRnsC6dIl14WZ3yNrC3mV8NRrrRxROKJu9W8NHBkm4Q3Mv3mGwclw/5tqzFaSpxcPunTquRVlJB1lalrn9YDCXKMVGOSJMPaqs/5zxhyKLUlGHwUbqCswoxF/jF4tThBQcmh1JaT8ggxZjBcqPbEgs6LvLjPB0Isd0DqNj1hDZ/+Hn7Q7mMJqOmEJdhwnbhBsyCNyzW8qdMM8qOQz/YEjQv/fgAwuTHEsgFYg2lDeSYpi1YRbFAd1XtnfAOTj6ihkmRx5fKNsmrw7w76+bHRSy22KDrGTwboT/gwiznvs3IzIXf4431dvL+ggA0G/XNeYPPx4iUDNM7DJ+cLn13EC1uhAgL2Sx/AwKdJLsRwSY6NCIUl8nUvuW4D4fETbnFJ0Gt6V1dbFxYmvjO3vd7ZnYPgU1SF5/YZSosCsFg8+WVqjZTUARVfM4QlyHa/1pPE+QnFHN5NJdFlAEq5ks/PjNCaEVDsvpAqUWBV1AaLSU/mLsdaXf6IjWWTo+3Zkc2wEA3tUoTgAOHPO/NzoFbXShc+p9ReF/TalSx9Kp2ZL8Ew4VO56bB/B1xgS1xEG1AUZqIq+2Ngnoo6U+BMMZjmL7NXBQseyawA/CIP3cdwucCcVGQCQDUyB6AWmnfX/ftE5jqJoXWw87GsYmgVAzSUlUCtMMyztRyxh8DpqOel7YhNw9LNZDDsj80DEVAvF6sOld/Gwn1kogCTtnvw7h+U8=
    username: AgCDSQfD3LySxucH7tg7jD+0YgbF3hp0hJusrJekxjpgiFG+UHPGWaTp5K1RnsMt31L2saSiOXx08rc10PtvCLeAifQbKIrU3yQNj36gMUUoxF6eKx8xAdwFiuxiWjLhGAO5/cC9EKAALtXGDqvdNqz0CZxPB4oY6S1YaAsphyA0Ane8ubAUtcFdd21p9U0UC6OISYAi9CQjTzJv+KYMzMv4T9TlqAvrsfOcFLahurR9hKwZpas2iSgPllZBNsLo6qBPjOZxRWXLDhz9YcTJPp0buYGx1zLFuNY9ZljQXahntQBg/XICvD/ZgmuWk0Q5+Fam8zp0OVEDfGCg6QPRq654CoBObDOgpfZ8XutU9G7ZhXfC99T+lBmr+RVzZoC4DxXzJD80LDeR0dBTVLBC8y86oPV2mgbEvOsEj6UZ3pyN0OonPa5rKdWaxaw+yndyykmZMcd0nlmV8CqfUsSHitcIU/tD4PaYOKDz/wZURFTZ3fN3bJWyYctijtoA6vQl7aurNYbCEl8AYpkHF44Wcqyz5BEiDPOwxAaXj/jAf4yNkIj+RNbx51JsYsLoMQVpA59h2zVWl2WGlHm8dxLc60NYqoUFlrnKoZPHyPZgYJRMVlMSYMc9s5ddoF4OF0lNJ/7WrmbIzEg9cvKgZiRE+I2GHjnmVTelNVHzzY8hlhLf3FQpVVHQmveC6/R8pakDDDdCFq4fq/0=
  template:
    metadata:
      name: grafana-cloud
      namespace: common
    type: Opaque
