---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: github-dispatch-token
  namespace: flux-system
spec:
  encryptedData:
    token: AgCbzTPimY3y/sAVnwVu7ynvI3WnDoJ77W1FSgPlSyEAXfwlsB2Eiuw7+FUfj6L7SQKaymkoBM7ykXfy4dY6WzNBnY6FJ0qegCNLqA0yqmhpg0DNOlYiG7y9fqmEBUZamvYXtQFbf/tlS82dgDM1JzPKO4OXtTJrhnrPE7bWxy1QDaH9gxMzWrxOZ8iRCH9RGPuab5FI1bMAxVv4JhOZ5Wust2fYxQEo+CbXO3kPqAUzb8eyP6gJzHcQqpx+7h4xodghHtXijlYD6dOmBM0N5PFRg4JNPuX/j355D7jP+aVgAt2fuMOLOjzrCn+H82reTZaA5WBPIWGmycXo6wBMlppzthoKw5WNGJzgPyswzYKFEH/x9s/lJ5BlupJE8kmzeyFH7H6K0B3AYPRiLcDssPmL7UakhzqoEMHsBC7jZNCiIwiLbBvyhgZxPWCa5yeOKMehFIqDqTO2dxFsAIIHZgeaT5Fxttoc8G3McpIoI3rdmxgHgSEXI5c1oa4YtnzuHUaNBBiPPgozx7rJDqrKgLCj5G4P68HlV82FPnmauCX2LZz36JyjCpsAIlZ1tfDC/3iAWRugDCLy1lnZv8R1QWop8SUT2CzYdjZXgdzXiFLc0ESn6sDh738oRVzohL6htyVlJXjUePXyhERpyTyeobv7c5IqHLyGsfQrTnIVP9LEP9X8+e2hcRZW2wuwLYSApWZG2ku9dzgzgXrLZneNibmfJGMdnzGUVwK1TZ36XhOoOuIwqP1f2W0256SUltoy8SNU6EPZSdgVf5D+0ervnDhz7LHLS04CHv74lLX7XaEZcd7rpjaHbBvM2JtmwJc=
  template:
    metadata:
      creationTimestamp: null
      name: github-dispatch-token
      namespace: flux-system
    type: Opaque
