---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: github-dispatch-token
  namespace: flux-system
spec:
  encryptedData:
    token: AgCings1eUlkt6uhozfzCmqqKOs5S4X1Jfff/1Ltm7fxh3dpdBUddCb6xJUVTU63IvTeqgLMWjg2ljcArkvSxhgMaPG8K7y5PRmONxUwKjTVjRIgAvifFyE2kJC3LvodMW7sYuqJGnC8Pg22c4NEwFORuT2j027UfHoIcfwnndH2JTlob80zs5O0eiXmHwhSMVI9bPGoqYBGtnVH+E1qOBkbMATzgdoxCE408XxBMYtVGrykEzJ/Uk3mcxbi/Aax3gHop3XPihOnYtTiEjnqBgniU8s/NscgL9skL9Z806TGzvuAJS8eFvJZFxmyNS/vBUgNdV7TvZbol79FWeiOEhNX7xg/Uxo4hrK+3R4mbabZojDebiLc4q6R8oIczyY1snZfN9OXnGuF1r1b6nvR1OQXk0w8xi2AK+OKsfgVNT4kau2HOowr/ISPs3U+OJ4w7r3RwQOofe8gLWjJfFVkkKdlKdVHP5e1+3GtBQcYolpRSFGrY+vru9TXHwoaE8FlLeyd6n1VduWVCT6ZdnAuUg3HBdwEgKgNukaU6stOsGS+KFRMcdZvbc3UngdzsFhg5gifL06lxTM1Lq3oiQ1A5AWsAzA6SYzqDZIGvBGUZEeecO7Qaw8R/D9xHB7u3MKcMtc3tcEPbNUPTxEhkS0Ar7j8jjzdzvP0TIrZ7nwil45PZcBzorrdhe3yJGNcGaBw1PvDSYDSpXsnWMKoX0jrzYUp/zvXJlrbikj5SCzFmMmV4hGlVuUIps55JoaA3sD4jiXAcg06dvFqNskuCAO0Q90XYuNqkL4qBZfigUl1mZep0yNR/u9L7+fZRy22igs=
  template:
    metadata:
      creationTimestamp: null
      name: github-dispatch-token
      namespace: flux-system
    type: Opaque
