---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: slack
  namespace: flux-system
spec:
  encryptedData:
    address: AgBiWD6LvWU2H58R/m4OSt9DCgzKe1AT0q4CD9Loof/QY+Lr9vIKvqdYx7TMKt0kbopEDm6PrfeVI/w9HBl4GTIYzCv8T64sv9lDgF8RCngiv4ap46u9CE/G9L1tKmZ6HOiekQXeZ3Xc4lyzjHOo3kVuGulUCjwFwvF5xBXuHhoGLm3t+8XckOWAkhTMHoY/LutWTkuI4Eqeb4aLXEEBg7hQ5z/3PjSXB+ZIepgTGdfEC0+XK5r6Ia6pUqqRNLC1GZ10edJErsOKBY+o2In5u3+3htpRCjkslxo95ZpRysL1YartyGy2Se5OawJbDmg0Tm3g+54aqjWQwfHCnw1yS7fNam6/DJ5KGvtyhoLqwkfMfIAe3OfHHSM6SKuO537igG2TcKX20TODjhgGwJtIviKgGrYla2mf7eKbiR3+GIVOLwwM1c1hq2fDvpP8NdEIQGiF8shkNzQmWKPPZOdezsHcO8U0s5erTx+72uNMKuFyTy9498RbG9gQZZZxT7Gj8uAVBdI0iT35toj5BrgqM1gwkv8xs+KvP8f7TUlxOEoTnzt2e3Mbpya42csicH+6sq5fMAb3SyD4r3zp2GWOnvrLjCMRa25+0QQlYpbLLim4ZJhjjuZoZg6U2hXq2LQmDyvp/VVC8gRQJDlsh/h1h+8W9OLVN3rBqrl1/sZ1S6jkxxlWHdtNQKeZIV52zbzl+bouJkfxc6qqAEODxv46np7rF2QTSzUNxMd9TVTJwrZ5kEV8CfoMYw==
    token: AgCZy6QjjDjfmazwSxzvo+52qtOTZUgYzh6M5F5oT/Ypj/ikFRdoEKiIjxyy8ryrAdCmaz9Aq+RObzpcEf14GicO0r3dFYns2GcA2si+i5YyfJQy7fIH1e216JUv5mEq0KWCxV4rAswXHb8qcUOzvBnZ1fgdUsb5rp7rvH1vH4Df8HcB6eWF8LMBnARZDYbEKqNGdacaihAnFihZnfpfHUUh04XAlogDuyIfkZVwBasc5TgMMjii8BsaKtlHEXIvKw7FNzADpgRiodSMa7M3XpRpJQkeHHu+cKRKWrYUt3BH7m4PUsrX9eQijVBS0Yo7cZqxbcoBTd8ZEFu6H9TPqeDj+aGgGmLjQlPzYmJE/cTv2264O1d2yrCL5uMRuXWc5vbo8nvzhFGuw2NgeFPqobNfMnDbLTwoV7z4TOz1C36qxnh00cYBOogMoq9B12uyvetgqtIXwOnNaXtjIS4ZflhL8SJh+TQpfR9PJYjY/FBq+6Tn/LEV7JmtGwRhiH2v3/2KygYmFm89Ui2EUNRYnTT66N+IDgqE7Go4cBnIgtmZeAOuHISgkJSRe0ARXpCPlZ1xxzmDCu0miIJ3Kd5L1lMr5zwpBMu4dkhwV4Zkh1PPd7ZSv6BW1S4styXOHpiSbZ0odEZWotZ2c3wWF8TfeZwHOIcMAGutFe7ya7pzFl68ylDUa1Uumn3EWNkB47QieJRgROOYykFJwGfiK5wG/O8g+TPzLqAfIhU11LXZ+crpbuML/P3MvAihqtRUtjhhS+5zo5qYCGtz3qo=
  template:
    metadata:
      name: slack
      namespace: flux-system
    type: Opaque
