---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: grafana-cloud
  namespace: common
spec:
  encryptedData:
    password: AgAaWFF5h11ZZpm0WoGl8GMdg8MQqke/jlUO3Urx7qJaNQcgxHuS9d2VzQqDkWnMMuKnk6cSlluJFJauq0imGknCbrdbFr9aEQ9QWGbkr400Gibg+HX09kXZ4tPlDrAxXQzK7b6BynY/acUCdUldu8O+4dk3VOwy/AX1Y1XEeWHeq4mbr5rMzru8xfBZRMcDm3fwJQFjR8wqGf7mPQ2C2j9ykW6yH+aaJs+BRSuxCErbnug3iixH9cvfW4WXD+8FJTXbvAXaxcwwsipBIz8SQ6hizTgCEd8R3oz11M0A11WHRt9gjSwTpShiZqAtPEk/4Me33pgqF4Iciez6kRzLAO48khIGBMKoMoQ3U5L9FsSBjD3v0pLhBXlbPXAggz54emkyZUWP+ZuUbclwNZM+8HEMKo9sGY9He4t+FG58MAun7j8bc7CLkwfWjxtwm/ZnU+m4SOAgDFkECq/m/ozapUr2ijB3BUk4mYPFlRpMbYGt6hN/Abu5EyNUAW7f2Eqa7QTqKlRNsNxfcgXdNf+gbY3wkUBUk+1n1H+ft51LVD6gBJ7/oa2AMcxTVZyERAJByswWdWvzO1m02KJV+MiOtkmr6Xp5TyqGddc0TOt4Fuff8hJ8FeihPXpPrZuyKztTAGarr4SdhjuscnyOnW/x32UP/lg5vLxMSwvGvehDZmVO2eWMto4TBFqoXwHnJy6ZM6GJ40uqjReuyKmMcmsmGzy8vmUaw45XPtkW0ujn9+IO4KIgH3dh4OH2lqqcfI+S7NL86mjIAuP0XG5ldLaKL80dsZhNur5vi8OAEyciSgyR0yect2t2gxa1NwVihxejERlHWB9SaLt0LSK9c7sWRfn2dDfTMSnpYJw=
    username: AgCppbDD+9Bx9YoKWps26QgxCRmFPQwX9n3AyT6U54ZTPXzmyH09gi3FQh1HiGQ8dywXZ1NWJsbXSlecWMKff5SlAC9KIxh1VS4HzA7MNDzPei9eJ68BGYX7Es8ENwQKObeOksfKBBmz8vyl/fn4LdyW/P/C4lRZyaW7qERn3kLFvtXgOzyhv6RiRx8FrEmD4MLvMLTU2UIhNIALvb8W7w21vuDsBbGJUeBZZSZtTAcalzk/pbqKz8RGBW75HScPxCfVZn3yyXqLo/gZihxOSLnpXu/ddPnwqnzLL94a0z9WlfTMYHeL2EPhtPiiIST2t/dHtyzS280dl7pi0sixI894rDUAeRAXlKlwSFJhovCqlaIlX/5j8wbDuO6BR9ESS8LvN6mQ3a530KJWM1yaEYZfoqvozoMGREW1O7aC4EUkpzloyMHhkgfCHnGCGE6NI4W99E7KnLc0CG3deHmuLJVQoQ8jkrn63FtfYnFcOUL/TvBCdePzE6TuyFqPONH6l9eUtRBcJ3vaT6rZpyXJoyjYGCmfY/O8/RTUbYRBGwq2s3LCU50KOQrWFEue8+zGAxQRrGZG91z4JRoPXVuIZohEyofzvPPEGigAXG5TbyKtwpy35H5PlvfyKWmQxxZD6aIxPXmu7tZI5LYzpHU189Y7odm9e+fphK3Jlv2wK2quwKwlFMHGkSF2vEggL7g3vbGVejD1LOY=
  template:
    metadata:
      name: grafana-cloud
      namespace: common
    type: Opaque
