---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: slack
  namespace: flux-system
spec:
  encryptedData:
    address: AgA7ZmOOVLj8COZU9UDIRi/dJ2PXYy6a2Hph4Jkdea3tIohkxRDoIpHSUaxsVvMcAKEXsf2BtxRFkQfy7xXpPWcXsHCTLASaA5SxYX+xw6ePVZ1Ot/mVE92xHaGNeBwZ9WeCzjnNYXVC3EzptVxc+rqdMcHw3+4ZuIi0TwqRPGt2H0yV3VC/rlJNN+c1sQrfPzNGRHO5wjeieIslJh5bBMzv5jc3ykTYjdD54GVS9EecgAwZ990PkbpfrmDVwsp44Ru4uZECIkeyaXXWBgq4kHSONKIJJHtjY2xhYPzjpV/l0Ml76V9u+Y+zlOm4HsoS5SFjCnG/5Y0k62FJbFmlB9p5ww56Y0lCMDIBALCXULL0xaaHom3uFJxQGkKJxPIiEj0ugnTtpYjD4GiKnWVpCOoqKP2vgKZ0WFpJL6/N23mzOPbLEJoEU0N4AsiECGOFfzFglTwjGu6UWqbIcXvO8agELK+zn+HlarHNT1X8sv3ecQykI/H839O445h1ymPWiw8tXyuc60thIe4ISuJm6lN2IWJlUXfAFgKvbGZ3KPLyGa2T07jhbdtf+XAb6IabMZY3hhaJEKSDsM6KSEFp/ix/Xjk1VweUdsYNj8EzRm5577TCAFlZfCD8upf0IxENaEi9DpCxJEGER8HwekPFA9kXule4IuXz3pRsj966bfCtkh0JXj7I0a/fvrj4cqSxpgJNNIuDzmFWYlY/Uv/nmZJT6sMufartB1KrWNHu5Tp8GWyb/Xwp1Q==
    token: AgBd2vLUCtgObTHVA6j7Yo917sQ0v3WADnjmwruczBC51Cur7hECdCtqD8RWeggyxYgCnwyo4nF0abgnEO1nzqNFFlQdWj0dOOupLrzsrVesG1D+khTN0QSJ7dJpLr6SHBlSQVB/W7kuNmOfIMJQJ/s1DGhLKenZCZBY89RQ63hJ5wTY+rd2vYuwfv2hNqLjtTO8KkNquwPb59cXTHolLRDwRuebLkzFtpn151kr5hIneopLc1dwYxuX/7znIS7/LKNcHg93dpmyyyP2Nsiaaq7UYv50Jt1CFS+Mya6qgmKhWFENodnsB57IMek9gX3c+mahrk4OZkGsazLFKZA56rNvywFVVnqAUTHYYia0XOfXA3ayOplE8/cbt+hGfu8X0KTNtmxBO+FuOiKOC1nkRGK5kNjwH+LK8T/NHKOnKhtehTxZlFDJnum6GG6OsyHjm1KY6PhDsp9rE5n+KBSUEWzM1a6/qH9nCbbIVolrhXhsOqHFd2pYar1XwuMCIRkm11XUlWzmWn9TplZ4Cka6lloLvg0kY0O84AFsFQp4LisZpczDONeo25M4BN9Vf65dzwnpgO3P2ZmIOYFyhJR4O8ixKmnUPn3C1AVpMqbH6Dzx81Zw0/ep/BsuMLvS3u14kSBZiHRN2p+oZ6HxeSvqNZWmT52DCz+6Wo/+kzHzmo9En9QvBC//FU3SJhkrmmtOmf8IV6LaM60u5vACTL6X9sYw5n+JsCdPKJv4jSVChI0zxG+PxsbJlit+5884wCjWsRuX0qcvyxwSDd8=
  template:
    metadata:
      name: slack
      namespace: flux-system
    type: Opaque
