---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: slack
  namespace: flux-system
spec:
  encryptedData:
    address: AgB03psSAyvibkj1DL3Dv2wE5ERPGTG9f5ExQSaQkRdt6u9FV5mwXE3qlaZIyzo91/AyWm82TazYkEeWpwSSDT5bFkrQ2+3eA/kdiMJf6cSNAH3Wd9Tqs2L4u2je/LS0vp8YsUISz6cfpzxInf6X8D3B01mV9knD6cldt+E+hk0AGIOmJL+c6fbkObFRdE1VkyfCMQYtixFGVy1Ic5j/Ts+BIvyjxFEhX1lh220vg/j/Ak+/Pho1Movtq6qAfMRQ9tLfmrZeKepxlf5UPpVq6YOvcEFLZXnBvJ7CWJxRlBU2lxiNflUwq6MPSkJFjqbDPWgGNWUIuuqbqDNP5vO4G5zHIvvJiryMIZK8XHk4u8uUR9YNXKCMMxrSFuMBlUvnII4U4Pm0Q+MzPeii9P0CYEOMNvAtaIEiRWvAT3evtf500YLwFfC7FeYAqf1idAJbAyNGf7BzzhXVWk53be1bN4CBDJzQWa598Ho/evhJxEmlhx2QVaNKjVp6o+CM6/WEiPp99EeS2nkQLe3ZFHHRXEQ4+m4ExQZA8KmehNargebniUbVga7mQBsfHYjXtVEmQmEFxLRIW/5CZP+DQkcoeuQsFhd55zaoipX4Ep8dnSXVrC4hT/wM6KcFsmozNdxVA7rKEKKAuzIpmWE88029C6RI4Y9okOHWrJFeZnuGLz7DywUz5d9sdtAzvpMIB+Asn0ndHhz5Okt5i7BPSAlBU1WJOqFsaFHjDGnSWnZZ16ROBNv/nspkVA==
    token: AgB3VJSi16iNVBN0gGCAf7WYqtzE9lmDHtXO09+1cNYrwIBJk6rvTfnFUsQG+D3MIuz6Lfxm8izUNQvjCPVgXkJFyfMbSyp7jlZ6MgY5lqdp5PYD7jfxi9pWC5b9GT+CwDI6GmbnqcTyHUWyyhdztvSB407+jPkC/5txI4LSEK8T/8Qks8JRqYqmAOKnsLbAE72CHDJLTaXCnoNH95X9iLZY0iDo9nVqhUJ19XJZah8ijn8qa+3bB4oV6IcKC3+GJRXEYFyH9FM2ed67ZEQSRp+4bjDpA3drE59+oyGKmFQSISf0E3GfW39izJ/T3g5Zy9U2WezE4SMXzqpQl2lmvN/nJQJ3wU2P0to1zkUTgMG0lfb1VIb5jAWzWvWkF0XRAgSTMn1IZmPsx4/IqYJIySpu/r019IcGye3VFxUElo9VgN93b8XS4Sx3gktvwnnwNB48HzCHWBsREj6UBe0SbRm9UyR/V+T0RqAdrxkfXWhIuZqU4noVh0hGKhuT+LdQebaaye1vcYdaFX3OXmaneUJoRUsmOlbsj65holDh3/RROxcDlC+rgdUy4iD6Mi7Vn5qF0HdJ8XVEA74xVfg02xlq58EpSOhbyWj67qfAN2gIPzmhkFHxRpIVKsVSq61uW+d9imdPWw6gJz/A82qwIYnsXMFL7Mt4NOm9Z76GZx5vj1uOKmIIkY6BWKdcm6qne2Wh26Jcxbh9oQHD65EH6jLd3brj5yO3pKqI4usLHOX/GdigujctzATeNW/nqMKpx2+jh7svr2sY/qo=
  template:
    metadata:
      name: slack
      namespace: flux-system
    type: Opaque
