---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: github-token
  namespace: flux-system
spec:
  encryptedData:
    token: AgBJ7RkzsnSyggMF8VVElM9KSNMDs8IaZpFG54SATq6Orqzgtb70b7tXzGoPSz2eF933vNTjvWfFvSwJnVcYTmi9yGlu4B93JSjhNeXZBdARghAAJsJHRzTFmxNWrbiq4sLfLd8679GL2kLWBLgXgv4NSrDv5CqYZnAWqMbAPKjUOX9Gd873U61avjdSzisa5qlvQB4QbFZ2pEDIK63p27fbRUbGQYC2XMoJIyu5pghIdAhn1+4vmNfmD48Iwy8wEWDkr9IHozJLH9i3eIGszSW5S+WW+nt986Iy1PP39OGFSyCA+PpXCqmvLzNYsX3LYrkLVF1ZEFXwg0LPnfv9Kjg0K+HU29Qn/GVpqbAhVjc/0jXaTkrfv5Xh16UAe6WpcKH+4xQ8srr2JuSP63eG9abOuL/IxYIN4BiOGxTDhyMSjQfwVDt/D2ug7fJrqd/KcYJppzvoavAYKAO8h6lxLOMmBjkj7Y9kPXPgHNkDQQvUP7pOBk+a808K6eWkPdncvoei1nXE9i3kTLW8EBmTbve6kogMXOYx0ACcZNj+e/y/Dbo9sXchG96wH8lfY0MsRUGNbFP35HhGSmTzpVbSnivAsRIAcA0c6bkBOxme/nudA9k1tnyq1M/jKAZ+Dwt2qSBDEbY4uivUFbsJlmB89lDp4+qo6Y5aM3D2RNKc66HB22VfyJbtoNug9Y4HcIVtQt5GFns/ZOan0sWCIJjWCAuw4GhMhSAU6uZJX9jIWphI8e9whpGyIyD8gGcB2zsEkJl844pQW5G5yWfGFDWt4UkJ8kVVJdrwh2lkqJIrklvLJ7jH/pDIkLAMB2N9jlI=
  template:
    metadata:
      name: github-token
      namespace: flux-system
    type: Opaque
