---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: github-token
  namespace: flux-system
spec:
  encryptedData:
    token: AgCIMmxR8Ln8/bVsuFREdRQ9x8uLS+lmpkrOJAeV6fx51NfUdUbydQwnSoe5AyB8XhmGkj/j9SEfvGbNNmx3+nEqQI9lSh6kWPRQalIzYFxYUzA7I6nx98FpAOpItQYDC6Y+huoPD7jtaM6s2WDFtRhmf7VTHW1gbdiKPh4iHNVBwqOP1jP+8Ui76fhxEiwlVhfSpL0QfTJ0nTGwMDrf/QFkuuXCXuxMKvc5tvB/ADSXm9lARRn2VqNyhIB1zcF2bAUh2NKi06aihZM9Y0PTR8CUjVEztWwjy11ugSnA3BPoHF/JCx1knU1PxgEmqxu0SQXoMyNR2N4ZUKyT29KfcgLZhpKROFvg6FgH7ckmblkdtYCFrtxdg1ObASLhF5qdsmEWRzplSOQt2IOO7zNalDJ1H7j95vb38dkIbFY+YdYmlyKzRqYfMi1oQBF9FlJ/wrDWTwa0Z3E70Dx7QTM7zyVS1rqZPV+WLch2sBjql7E+tWQijwrScyFQ+VursGd1i8HFccV79ShIj8LO0lJqz8r0pjmZZUuX7dKh7MTCJkmQOfkJwbBgT9VV9iJIYmAeBGbM24pMo+2SRjQBRwcvx/rht9OGDMIJZPzeiQWVC8MbOh6scD3Msw/+ULxCbSeMtvFq2N2qI3y94Iojv4r3muNDsoi9bapWbpnYHA6Db1tZF4rspp3t7VRCzDRDcn81lA9txNFxFOsUkKxq55LG5Nvf7MSKBEeTIWR0v3vV10YblbgOLpNPqI4aRA1YKI9eC3ysM3EUShZ8WZ/iz8WVHmyjU5NCJ7MbvtI4uv8xSMBGuPdIuLGJtCP4nwvRSnU=
  template:
    metadata:
      name: github-token
      namespace: flux-system
    type: Opaque
