---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: grafana-cloud
  namespace: common
spec:
  encryptedData:
    password: AgBH95IoKQrbb62eADxfV/VG+XScKAmK7YuBfjTAAuWsYPfrmvpOJ6ry1xPOB88kGAy7Eb5nYZHHBWiL0PupI/pZHmKgvf+mJFOopD/c5rIaeTBIORBRxKWGMqQfqkBEcG4bagXxBWkkQgGYIUuPtzjYr1r5WGRk7bkqiQQzmlVt80BzoIR81q5uDh8TtSIpI9CvEyJsRmQUK+rJVgtX8yy1As0jT3YPWeo+nJ1hSP1+oe+yeB2lCETq+1mrXD/QFiRLJQPR2WA6DPMdqgJOJNvX81lJMVA/98g/B4XP3A5hU9kZReZKp99hfzXQ19BQxQ/tUGZ+FOdMWiuXE/aMTbMi4JeltQIp+GKg+4yCkkDB88ap9ImoLjAQc8ICY0gYR8tsTGRdzy9AtbFW50PwV9BW+YfyMjJN8HYI3Ol3pzQJ1hzZLbud4ksSbYGKijstM5L9W13cd6Rgnh2na2fSvAjUj90iqJBm0+uzCl+euc9ng6RvMGPABJMke7/vmx2bYbHe/55OSUDfqdqJfj6VUrHWH8knA8YWXJOqnqpktt8eoBwe4Bzf0gY2MKaVMGEHqQSMm0WT99hp1/s9eP8hQEZYVuYWhg5bLwCe1UW3paNddtxvg2QsqJPVBD6OJO/R7NFmaFV3y1nvWc6EK85/XM4uHVY9Qf3fTvVzTCA03rKKBVH+F/wCeafdcBgrGDTUd9fYvf2QPTQy8M8BCjK0886fcXjZwqA4OSweUBF23H1aNiA2ZEMeOVw0vr7E60SNKjh8LsAJOt9c343Z8FMov4aRMhASjV1+m4V/pjyWjZDbF8o6WGW4ptihUkDyrsPML6EqffPCUYCCtXBjVW4XBcLfOdXBNToq85Q=
    username: AgAVmNTeavPQ4n9bOXtyfpFzmZBKSCvEbpOVb/RepJ0j5PrpT2jL5SVq64slY7rG9FOf0N2zCKG1lmxIxE1x+P/WH/SmrE+El8IP/VsEfsPOdKgfQmXBviF4+GM2uG9fA/G94IqHugNTg6JXeb1YuVNjgbLkzgdxVwH7zYGzOfDUmh+Uj4jKFNWnxkIk1XzbW89J0krSerSWXuSI9dSOL2XyMbe4qhRtAaPqGOmHSWDq2wevi68Bu908uAnAnl++2B0rm+2CqtdGjppCnHJLv+mpSKszBQXj/p6+keplLP3LBGUAHgUa0ePpzwNtM1KZylGJUoIqvKjYUrM4h9vhtd81lQLO5hx60yB3DfbVXqC5zq2DAIt8YoE+e4xj/vfyc8cVNaribuVajwVsYU/+hayKisLntK3L/idxhPIyUGADWZVjXlDbJxO4gu2zRr1zpQPWYBkAh1n1LIcBzVFHoQACU9ELYbngqPxu7Kql6ZKf6V6yRAtsZSHATMaYi5dE9gu4rV+a61IVf8olXJENFi/aNqmg4AHWsxJ4LY5sYj0/BSzHsIX1v2rUH10nYPoXkWQQOyMOTiGRQcrz3e0v21/Xcn1ahLVY4pcCfgzsJOCwI2qnvCuwUO+zwLO6SMv0XyOfhhGk+GDlU7hrrIelr35HaNe1KFN0x3GcfVZozdJzhJJIkZn935M+LiMsILuTRDcsG68WKBs=
  template:
    metadata:
      name: grafana-cloud
      namespace: common
    type: Opaque
