---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: grafana-cloud
  namespace: common
spec:
  encryptedData:
    password: AgB+hkAcWFkXgQXyQma9GhFeYcwbM8biQWUPnvzBXXkPBC6XCHipomT4yoFBaH8ngS0zgZbazgcDUQ8TsMGGexQxdgMy3tpkK0gsNQ1bzcfn1ZCqzasnwHiLg0VZa47bbAF2jcYo6Xd7rdW6f8VYGoewWwARDEUvgs9jVt9O7f0wXY5ubd4cuMge3F+MKBeYd/10tuMIGV8hSXJ0zgTolX9t3uUKqIn5IGuL/dwpy5iJ6oazrufxD1YIiykVskbAajlg3qPa/CuCWXTVx5a0nT3s7Y9a/xmaIMhwzeUPdw1Len9DoVM72yyjwzTU+UFCHxxARwDwFIjtSKWUz8WJNSKbm+qy0rQBjDRQqY2BeSiAdlGjUzUl43TJFho6WJlS+jPKMPUUJvt8VGyi5FPoiCJdNwkNuE/iw+RP2iJNYbD1hZ+GyrjVz0UdxpgyKyErPWO6n8z/GeYxWJ3Zz+bFOTmKgHIGXo14l21j8z8LbQ9wt7rCG9deQwLtFex/0KCL7w5x4TFeBh2adGZ8vzfsDdxefP+Sshk0O2csO5f4yCbhzLY1N8/ajYcWbAc8UP9io+krHtmTHWkWDawrZR+H4YfOfFQYPHOjztkv3m4JIqC5OkTrZLYsNbEhC4ZOrqK9drGAPyu6g2WMbBQwB8oTtrRkVG7WNT21FL/RgPCf0s9VTOIAEm3F/HBKO61Thw9rkFOfju2XubYbND+VIWA75YCcFsyXq+lSGwSzVA0eQ9kdBdNIhb0xNhfr2AUJ8g5ZjjANZp0qqGplZfJACNEmE8PFrydi6olalOy+NjVKsg5Q34iUKpHJ4vmW9Z7ttho/e2rrp3HLWrMBH5XH/YAetw6w9FhIjw==
    username: AgCrIOgjORYUQH8yDlM7jyUBbn02NlI5wdemyHX+cBrR+NHqsdgeLHPFnY8tI3LeQPP45D3DjcuEjQp1U/7FBrfjD67Qe18WxE3YLK0HbQbF8bT8cxvyqbCe6MXxDoIPjDP+Os0wULE0wGOM0YUXcTxTPPJILMtXsIZ/AXDsYylq7q5KC5sxMl81+c6+/guLc0hVF3jrZWQn22PM1z0d76Ldhs5FqhijT2GsoW1YCFFihqEWQ/GJ+bunRyK/N0DELNycKvHCXabw6Hh1XDV6j9H1Pa9FziCXx80JnRfurA9ykQU/Sg5aAyZZBQhzS+dIbj8TRk2Z2ZKxcZuSlcr5pbi2Mx97p7BCW4YLLrHr2ETHWXJKsWiUmZTiU67tIt6qoA7n3hm0yKnyT3pAZO0bhM44MUx1k5b4ASfsOTbSEJ9UgA2Zqzj2oZn2xrhO/jTEnHBKvH5Naihj3zmbj7kUJ6UcucrYc7oWjZE4q5zvminFdht8tA/has4qSTqPtFlOIp31JYEyjFuSF6BwQuSBR+cUB0OBfgIvLvWTn9wzv+MDdhSJ3pwO3q20Rq9rYSKsLhgI/yv9TFjYqgOh+1FksLYYJrqTuaBn3F4MAhA0H1/+voINMvUR/c3Zo42CEkQLfkWkZlrAEqY2LN+u2RdaXmfUzc/ex8gseWlZ4Wt+XJrp/JiiR2gP8inMmvEtMRknl8EaVwzXR3k=
  template:
    metadata:
      name: grafana-cloud
      namespace: common
    type: Opaque
