---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: grafana-cloud
  namespace: common
spec:
  encryptedData:
    password: AgAgoRqxHgbg+ia3/o2hW37SyWNfcxzeglFFx24uOt3HX51qZIzpXIiox5h0CydOgrAXRAXE0i+TkJPtFh+V8CGv8ZrbaBnt/48TUY2raWpvhSWLKRrFtmojdpke6vJ6Q+RyKmPK9JtpRdyG0OvJwSN6btaYhPI4rcXU0apHPh9gT1ECWqZJZsP1vhCSDnsQYuKPzCr6O8VUfoti+vqBKPG1qwujVk/uZdfopROkT8zlHd5NWiDlAELvLJn7y0XEA6r979gt9+J4cnE9KGSQ2dlLnFE248tVaD1Ba7xc+b7iU2FKzj0CM6/7ZpUxvtm7uQUfo9FyRhH2jcslGSaYhtm1zSMTNDOWpAsrZG54tLPu8v6qj20Dg81peFhhf3QTnz7zji3oCVy4Kd0S9l6Mmsulgj/ZajBaZywHnsdn76q08QddrVxEaTLIll1kzQncalTgNp4nZjWoNhdcHivy03iHLD4i4atI6LcVYdfMgDL6GDJQCXtBu9463S8Of3E7GV2YKoAhpYY5S9kKMBrzuifGgHfMJRCBwSrDQSnFguZ8qbu1XNttx4u/eSU1aipBdXZG5lYta4ZfHHu88YQ4aVCkR0+tZljj4bFHLafomOiVrzYex45TFnj9rDRmftHnFpZJQS8yuOcwEVtEcCiEEpzmgbNMgSQ8dnyMI1/LWqruafhTIra1iuc+WPLJ3ff34N7R7K02C8SSxR4B99mXiunMUPcRDm9bIT2uC+zBMw2IhL3kBun23B3QeP7iECkRpegH7FDL77HT0ptsrkXI5LI4iTYrPn/V5oYLe3Y6/VIF0f1oO79m+65ahw9oaoMhdIYIUoql4zIvH+Ai6quXCC0QFm8ZputJ+DA=
    username: AgB0NcZA6szfO2TFQFcUdZvpgbdcuWDHBILvJoimcIXP2uFT1usQ6jiwH1pRt/V2QoBiT5arDmblseRLpI866oADV4VtX0NjKcaMjr2NDFmRBBZX07hbH4PSaRIc2zSi2WUB4LbUJItKJkP6t4IJQxfpP6wY/9r0wIjRyOcWT1ddCAk5ZU138stVNE7BbXNxQc8JMLBtmZTzD6yHQvoj6MiVAnn74n94noPWaAZ4jD/sX2uHxk8m28C8LzZ0sg4k1gL0tHdLp+uoVkGUdQU9UCFu90eA7e+4mI3k4ZKABJbwMHc+O9YheBiESUtKCwrqvw8YlGUbrwFSm00yrlrl4IEQKP2lu8KQw39z9TEtm2cRiJwQZLS7kSU5WALJvlNPR3brCnGmkMJuUbYyY06tNzK2gprovUvufdGizcXikahhHI9R9NLBDbNZRLme6/tEI/nN3r8XoS5rs1lt7xQZZFSwkjkFOpUz+JIhBBsbjMLgVYD56qyqPKDU10+cv4xuajC8FMF8lGl2GV9ZR4O3ZegfFCLYrl9GHhgPN28dfCczzTnHMqKOcOu/+OeaaryIdm7C287XIJnWjvLkktRPPs+X6hRwvH+QqHa1edI6HNsGwTAr483C/gcAVDy/3TR9ZZci2jFYSlQOH2iNuUUfwu2XAuSw0yjQBOec9CoaJeeDg3chPyhuNJJnLuMj0njUOCCCFbsYlp0=
  template:
    metadata:
      name: grafana-cloud
      namespace: common
    type: Opaque
