apiVersion: notification.toolkit.fluxcd.io/v1beta3
kind: Alert
metadata:
  name: mirror
  namespace: flux-system
spec:
  eventMetadata:
    summary: "mainnet-eu cluster"
  eventSeverity: info
  eventSources:
    - kind: HelmRelease
      name: '*'
      namespace: common
    - kind: HelmRelease
      name: '*'
      namespace: mainnet-citus
    - kind: Kustomization
      name: '*'
      namespace: flux-system
  exclusionList:
    - .*Internal error.*
  providerRef:
    name: slack

