---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: slack
  namespace: flux-system
spec:
  encryptedData:
    address: AgBXfq8eQqqgCDxdy4u7UbCZqGjLq7ZEk6U2D3hwVZsqMQa8RxtMTyNzDQ395rptDPaPvO1awrKbjDRHw0ivhoUC/+gu5CCt/G73hg1Su69rE4ehQdxnV/ARtDDZ5zQYzl5EabUThvgl7+1/jfGDyb8NYymzjpbslQz+kdGXC2TbauOM3bCQxkWO2Fo+n+NioREGHzOBehN+EsBaMed1T1Me0BsFUGb+eaQT+NjcrbSjQwS45by24WoA7cMgUVofEr684jEHHoA334kmF+Bancnetbof5T0PXQjibRlOAf/clRqS0htko1CMHFk+L4lQYiOZkTOToOt9zrbI4+WnfM+yCpMqVlGhZRKY7BBeJAdlmeHCuxspSY+TlNTmZUQ27DRv30zNK48OLknVBeC02HWlkdxmquTK7OL+LgabHJOYttOxGAFaacm0ZU5GHSwVktDVAdtV6jyENLRI9WRriMY05QLaBH4MQUQSvWtEK7v8BkjOPgpzbN+oS5ElC6WpUa1lnIzsjGu4LTlRSf4gDWpRwSHHvqL4LmNanEc4zBQLSnCiMIIuZLCvEZzItuU3d/M9JtCHc6MUpa1pCc9nrvQozwuhl/+y58CrocVywiGjffLzWf420AGWU2ITrWzPB5Za4eELrgkbzxH0r7F7yorltlKIj3MBu2wIotPCI/kAgBdVc2vxMOwmaPU3tT7VeGwz4P8Vf9APmGtbmz7fM1MLy5NtmSo1u4Ph6hUB4Dbc1FAFqAL2cw==
    token: AgCWDtRysKVbQrwzs/YqcsIY3+YD68MkNAiUX0KEJgEoBjR8DvVGVf/NxhQK7AhSoSuDuz02d6YF0MWqsFb0+rPjytVq+cYuKnRIzxcf0xLMEwZqZDg/o9O6D14hXqCpwO67bYRFnN9dXfooWMdbAotcJsYTS/KrxgkKSJEzFjJLIxVBgKo5ClKDzzulHD3puj5ETElbvgvBkzoT+zBtaUesPQ/hXnGASFFVyrgGir2MiaJaU4anfIShBlMkboE4eClyqTHB9xTeX9r8gKaHISg04dJCm6qVna3EiNXfCqp5LiSdCxte2bnV99aUFk1dVux+luvXk8GHNSvZr/34MEy7DI8PrTeJ8lhto5rG6eyCVqKjOEyqYJcs45JQd9oWQgG7bJSmRyBnf2uLxbAlX9nxNTlXb97ChdDlT89XeXQh+3TvIwSkfuuk7qfXZdk8X1UwYCl8+3PsWZTejOnlX7S/jGQE/Bg6BdXyGTuYftwNQSJJKeCmrpb6xFgTCPYsCNcaGspAK1E8MTVApnZpCEyjEGvv9Gbv02y2/G5dPKc7doAPsI7tzhpX3xVeV9tJXQJ76Yp7lEnnC93Ou/GTOn/YofkO5aE0uWtFrYzd4nl/Rni2XaVG3XXzhgur+HiLSZL80+6HjX0E6v8zBjJjhrJ9ScAQ0hRXLwGIzpKXjsrx1wF1E1jW+Y+gEo7Vw8yN1aSQI0fl5l/KaFvJNEqdEzRVfMzdZuwORBhblI9146q2umJ9apzyGrH3U9KB6lNuxHJmdGQt6riguFA=
  template:
    metadata:
      name: slack
      namespace: flux-system
    type: Opaque
