---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: slack
  namespace: flux-system
spec:
  encryptedData:
    address: AgBxDLLOAKgJ+wHHWhTxt5nr39tGxQtl+cTMFmcXiXGeIEKsVksqlMGNBrx9SAze1+GzK3Sces6AEPrmu8wfypTmWC2dU4+/G01bfuMNvgSMS12D6L/ZyMvk9nhxjhfDWz4L7neQ8+NrsOEjhWaMsL1m1/txHNL5gExTLJz5JV15q4UP391WF+elBFsyZDwiURO8v0bNQgL84CjXjoazTLR5I1qlCNSEYlysoslNh8PdyHeHqhM2ZJH7xAq/cyy8Fb5NnvIMaRk92+wXl+q4NKp7VL25Lgj8hXR2XV8V6IcUjsIuO/YBC3HOWx4H8572PijPiwkY0zaorBCGTY0p01oVJAG+5M8CuLj3OWBoxlueY4ShB9QWeekZR2I5Zx8GPJntw9Oogkx2DY6rhbaxWpiShExRv1T6jxuPDgG+IPXcvdBRvvz347GD5yFrtPdDPgW83bckQMhttkm7auWQb8vH2tRSgAEP0wJHn+FO/W39FaMN6FGwv4lEDIwI3azoxtkmAsY3zdhWlawBfKYH+G+UXl4e1tPDJYyuuM8aH8HxCDE2jMBBj18z/IdRckdf3VdStCpeoE5OCU8pI/NntjjOFTKRviA3h4JraMkv9BtOL/W7e2VNb2sNXOuHlaadhiUj9hUB2hSLwe2TMYAsoLyZePi2s6DjElWA4EbVw0KQC0JU9h7ZDNtJCm7VEBd1F/aRPaI698b7exobBsvKv8lhGefYTiOAAZXB1BTrCljzZ08BP0Cbiw==
    token: AgB4FYZeDIjO9hyx2TxKF2k20nsRPoZAu8E/y+wjlWNRE18nxRDjpch5w0hsmMYBFFR3/5mQkcWx1XyeabiOBFnnsyK3ZmZ6J1q9lZxZfOWAzS07H1VPIQzSJUyqGSOVszcRVJuFqSa0hOUQRWYLqFrkCilMRbSex4IgsEbS5OPFyEAdZyw9DXrGnOq5gc/2D6eOu1davazDu3PBpRIXb/nbWgYEcwFFy1Ckzq0870l5fOZezPbMFt5kq/oSFuNZyzKZ4lrlsOisQ7uquRkqh9/XZ7wL0sHueA929UIRThn3ARJhYo9HT5A16/1hilIAco//Tn+VtKIRJU5Q/Zgcnl6baR4KJJss2vQdXwqm/dw04DbfxzVrfZYRWQOLoOyElIjmvtaTCs9szg9nWUKNXwRqA70zn766qOeHZLebwxmcWUC+B6g6gUtK0yDvxT4SpcgO4CATS+m67hzeNeszVchtHmrkRpH21Lfgz4eRvk9hEB79UT/oSIuEhhsnoLBjK/qz2fBtUL0z75EQdTMXGmXKnZ0coqWaOlY/UCARz9fd86ktRrSyYhLHkruulNF/8lJwXJpkq0ZTHGHPfkZeHmuUFrvibmimipJLE9JJeAxnGPRjtJFjnLneXpenOigGSVJMa0iizdclAS/F5QRPKwEHCSr6UW8R1GkIiMuF4Zx/nw9xAkGh6L8avTbWIFKbYb1ti9CAMkPHziqXhN0HPBgfN0Y2CVlEGNc8MHHw/gYu1TRJ3wNa2S7QXB0imylMzK/Erwd2gpT+1RU=
  template:
    metadata:
      name: slack
      namespace: flux-system
    type: Opaque
