---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: github-dispatch-token
  namespace: flux-system
spec:
  encryptedData:
    token: AgBW6ZlGOV6sZyLIEpcIRmDCXMmaVXJF1Bgg26Ubxj0CSc4CbmUUwqsW1CWV7NZqHOICrmS1DtzA0HD7P7gcdFy7RgWtfE1zSuitUEDKon720hRCEvk3A6LebfqEdo3tMfEugu7BTteHJBOdWoTjMTX50aBqPDxFy9mgIpXkl7yloXmm63Z08zJNqADW9N05+/2TSwfnIT0rG84TGvYH7LNhyKNRquUMlTZLodcwJPk97T+XjVEWEqDtkynsfojmu1voI5TpTvV03U/uip38UV98mW3ojXrV94ayYBhk8b0hn4kHga+3zEcCpiv9zVKidVJn0I5DgI1AFzHS4Tp5uWv6+CN6B0sbqjsUudhZ50g+1lmEQGYsojKRukuTa/3NZVeyZX1gdBEh/ttbyiKBpwLEEZ26oZMYUpocvJD//f2gbkAGixe6kGCJjqjJNL1PWyT21D4biQkj2cRzoNv4oq/VWmYW1rGPNY1bFGjiVKeg4O/JI5owCG8y9S2JBiP1UhCJJbNM/wFoMmktGWdn40XCjtDH8KFwQLBfMpZ5jlECstE6Fvj7+8NVO1IuWczXEB2izE15n26u3AFOelNu5pDSLFr/dA/OavvkEJ9ZTyy9Vhckw16Ye93Ov53kHKzpEG8nptsQOuFmvuICPuPf5l1si3/D7cuHb8vfpPsiZjE8XJVQhRnqpoAp374YTblhkveHQV5LC/68xQPukE2uWHv6TjN+xyfiLzD1j0TLWiCBLS96OKgVhtKimjAHmt3wDfy3PzLJF9ctJatkK1i+53FmPr8lDUIYUvmDAPo91s3l3Fs5s6apQShpa7/Dzs4=
  template:
    metadata:
      creationTimestamp: null
      name: github-dispatch-token
      namespace: flux-system
    type: Opaque
