---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: github-dispatch-token
  namespace: flux-system
spec:
  encryptedData:
    token: AgA8zLmZBLcLgwNcD+McDPbKJmMgArsejmeeHjLHmC62inxUqbODoXbH8+Vx5uT+3AW2gn3tnOqiUjEVayi7OOXqVK7Pkhi22W8aAtCrZx3srP7b8SKNdhJZFWbCPt5a2bmx9Kdb7Inbg8FsjIw4/2fuVBIwCAkdFIByxBQxuS8fI+u7jBP8dp/QCQewjUkO8QOXBRoW3K48u9JBI7+b49JRJym0vPahlpHx5+weGNerdVzeyqAhRL05mfERn18hCZxrZC5n54m8189pmRHrBcOW27EkRnFaweTUFHNoTQtqIXBboV7OBDMX0bIUsUeSTCowjD962lEtpN6g2ajgfYCIRKDZs0oeBlWkuWs0SS82oSBaU4L0PdMwySnaJJsgpH4tAuXX5P/HSlca3T80RYjGy+THbLiQiK75DcAo8+5CVqdGmhxTxI8K79UVEu8neOx+goWWlFC+Php27cgdy2qKeTUP94bSrZSLDgiWJ6C0n2NvQzceqxBfuWW7QkEJLbjCssv18+0/zb64cHVdZcU/m2XY1xlCccaVeYLqQgShAzCeQrlayRJqnJwhouBilnWGZrXgKbZyD5lUSCiirWjyPgsATIBpFK7Q9ytxG92u791X1ChmQtoiUWGPF0RCDfBrfaM49k1duK2jg7Hu3Wr6A4sTJVY3OafV4py6HeErjp/sKDGmM5D+87yALl2/d7mVUMUq3/q3GZJY4v9B1GmQyt2GbIlw/ad30uNhXIeH/OB6ILPIrFu+efiu0yp8h1oenqbfQqjG6MA8ax67obI/Ipnj+Px4Rcfc6mxWzYfzt/5ZKnb1S5Qpo8jJk84=
  template:
    metadata:
      creationTimestamp: null
      name: github-dispatch-token
      namespace: flux-system
    type: Opaque
