apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: mirror
  namespace: common
spec:
  chart:
    spec:
      chart: hedera-mirror-common
      sourceRef:
        kind: HelmRepository
        name: hedera-mirror-node
      valuesFiles:
        - values.yaml
        - values-v2.yaml
      version: '>0.0.0' # Update to the latest release
  driftDetection:
    mode: enabled
    ignore:
      - paths: [""]
        target:
          kind: (MutatingWebhookConfiguration|SGConfig|ValidatingWebhookConfiguration)
  install:
    crds: CreateReplace
  interval: 1m
  timeout: 10m
  upgrade:
    cleanupOnFail: true
  valuesFrom:
    - kind: Secret
      name: mirror
  values:
    minio:
      enabled: false
    traefik:
      service:
        annotations:
          cloud.google.com/neg: '{ "exposed_ports":{ "443":{"name": "mirrornode-staging-lg"} } }'
    zfs:
      coordinator:
        initialDiskSize: 75GB
      init:
        diskPrefix: staging-lg
      worker:
        initialDiskSize: 100GB
