---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: grafana-cloud
  namespace: common
spec:
  encryptedData:
    password: AgB0Ss8rBkk6RtDITInRWsq/Ur6JSO6w3oPQrIE10N6IMCx5FV+i3KvWYLcNvxXRpxDkaWoTAMiT87V3DfxNyc8TtCDDR0aKMPaQJESNidCku9fL/GSGHHYNBGQeruRcJ2F3Dk66JyApwA7dxu00iA9sHdR35tFqgNTEcVmDFeDMR91aZUIyGF/PWAfLi0j9puXMaipfHVIcH1RwQHJ40F4ylynkSgS5DhLcSCtS/Repq1PoKAZlprcBBEJ2AELk0aF1mahmiIex98KHy5tcIJ2PyiCKO6DtBzJSIlmaM40bEKbbHN2sJCVioWxvrgU2mduHYO5FX77/PYwrLccwK3kJQwkKLEax7/TRDFQEMEVYKvv+l+WBkqx5bhnfid91uFlOiC4EsUOiVR7VqG6zfMVfKq4d6UonB0fXlhvtF3mdSyw0xbx2KDr6ZkPhvaw1w1kk3zVN0YW+VUTSP0gzj+3zP/Y6zG3mAp0UcVCn815TgaOIxJUqK3yaGY8SfvJXjLnnXGqu2Qj5lEOegni6MiMJ/i0SNxYSR95spx2WFR4sVNVtBr26b975sy4xv5Yi7p1Ed5HhubJ/O4UrvB7+z+ShkePjpxceCBYB1JvDUovpg7WFruARS/q2yymNzl1klskzUgpCd/Nujn9T+SCm5MAdXHrzvx8Ka5pVNfbVEzvb8cIoOWtqOUjUqltotTFy7JmLRlMa7kfu34+RzXgpG8M9qnZNsnJ1ci26Hg6plNTKlSRVeKYq/YTFcLFF3Z2/Z3UVDsDJXXWryFtaz1Zh9myqvWHeBN95zIFWwreJ22eeBRwKIjm+tYy0D0IqGOaVBiZRtacDOqm2ZmVJcvlgk5iV1PR+aQ==
    username: AgBaZeBDuM69eJjD4U1camZJt4v2BNmvZwhq/5akq9MyShJj7TVAX91g1yWHHUl5PmxRahqujuwsfqgAlmoLnTH325fTRh7CnVPR9urCOmrFjve7ZYMvedpu75/pdwNDLRxIqDDvuLMacIhemyWn5VFV2mqkl/OgiItVD9DgjNtPBexMnEv48rCAUmbLbBEQKrtIyDLBdxCMLWkPYRJj1r97WcPs7DbeoqF7bo5LqpVngtcpm2fTPUy76IncDG8DnJgBqgWW/KvAgfHIr133ynPSZhxlZz9hIbm/5TzHOhkf5+vmv/X0eQlAZNj+WQoHW1g6ouF4W9HfUgHNluZS02VM7Az+Y2QWseTGFVmnVU7UpQq/3Yz7stoZHyLn5BT3uvMZ3LNYUbxUHt6oofoTPLzKQ+bO5IHSYtG8AfnwYocqzgkv6J9HPcct+i4/ebtLhUpIrFhFaPD/TWGBccSNJvCPCv+zcxitpc2oXSSKVTd92QqneJw9k9X0H4SE/8/dxq9aejo5zKqNidR6UurjWE3ULJRO0YWgh0j8HxMdyi4S2kxYEefB36Z9jKU0aT5xEkA8rFWGQfbMGgFtA7yf9xMek86zDSIg8AABWAWa1r3y+iOygYW/fOUb5sLPMSKNOeDaQlKoI0GOTDkYKfKKI176MCSYhh83e620bL1f/zoPDnoSb7RprcKRJYqFv4CpY8mAZpay/vk=
  template:
    metadata:
      name: grafana-cloud
      namespace: common
    type: Opaque
