---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: grafana-cloud
  namespace: common
spec:
  encryptedData:
    password: AgAqaGdRza+EGooX2oP37lEHpPCwi4sBciPU13l8ztWsE3fjcM7un0nG5HMn+snGp2wfij6b4lo1SffJboLs4T9BlZl6yMqvXCwQO4YjQupaasBmxy3bw4vk377g6cRU007y061qTMEL3Zg9qI0kNCg7SdqPtZfxCacUOCu1pyVIk/qq8PP94I22kTBbXkjOhvOKrS0rOtZYaQuIyuC3kSep6UDQpRqrSlkEV+/MyEZeoZTXEXwa6Rhw7W1kwdyPCZv1RLQX7zrPN7qh8D9yzf4NPh/pAp+koqaKxvLARv0VDpx1YmS6W4VzfCuJXPk2mBrR0ZHdcvvr1WPUAagfPy2EPZTAVlDz43B2FTH/VHj9R3YuTvMXfXYaCd1LpxdlZnB4yib1H9KMdgAYZfttC/ZyJ+Odh8SFVn9TlYlXwDhrl6FHNotuJPsu6Kj1JXs/bEzVhEE+V17URNuD62kzuteu+QFu/owhf5NNxaOv6/HEnb5jCybuZqwakgma02rrwZX+AYrn0VYJVoPTLp7UHyXplKGr4UuJImkmYj74AyigRVI+Q7BgAharCztvo0G4ws40ZUv+kzb46WdmJxE4DlFF28uBHtpg8a3LSnQ6pH1F8yjrZ26nTCwWKigpAMWX9z4eZvqiFM8FcZCThoayugEys+/3HItfVoSxLwj5BI3JZCI3nZceTAop1ztD1MH9vERds7uTs8EpgEK6kGaLvgeoslxqaAj0WsjuWWMoiEHJuLzSik8kzXxwHGeehwoDckV8Q6sk6E/Yn7AFgBrcaR0lJMEa2vVYKV943ChQXbjVTEdhmbh1Xx1IMWgTRh9+GZcFdzWnCe9t7t+loK/4IRBNIWkTCg==
    username: AgBSLylfAZzC86fOzroja4piT/34FA2y1bfOqEw/O1hYSxaIQa7Gd+jSl7bApUavzvFeII8oCZYxsYSWdKgtl64NJfo+IFHbtfyvBcRV8Yi7YsjgF4q5MYyFYG9uYEHbdxJX9jOXpoULlx77ZafoXoYUdbXju4xy7uhTSh0XtjeaH0O/jvnaMgZFnvr8Cgb0nVzyliq0x4JauIQYReJeiCTjHsN/LFcKMXuBLaZksUCukLmidFubIof9s4zpgdmNmp5ow9v+f+6TVT9DtVZezr3yyAec2cAj5HxGIhWe0rwtoFjACUHdpKjaZ/MIx9dFfJYdUEDkAEb0OpwWhhc7UURyibUx1YdAWabBRqZuz173yaN8JeQXSCBXBnOPP7WNmwfaUvJR97VoNWXgLxcT1qh6gA6gdG9jZJkwb4WyE8gJ0kAWSMDcfexkGVrbVzL/wYld4CkaHKPxE4C86kt+wYPo+o6E7Ocb9b8t51HeA+NM3Haj4fV+CSR/nQGeRkYuULBb0l2u7cXPjaorlQOOplexhIAWq0sYs2xygHGEplENSd7Xz88f8SWw+FLRzRXPlL+R3f6TEKuk/mdr2YUfUVqU9UhTytYhJpF7sHKeRUmKbJ7i+I7GX4HPjNZoauy1tgajaoGf7DKrhkF3NdTP6jLf7RPF3dVkIk8BC6+Sg30o371ZJokJVNP9/JIVDVBigDl3o95etnY=
  template:
    metadata:
      name: grafana-cloud
      namespace: common
    type: Opaque
