# SPDX-License-Identifier: Apache-2.0

name: Build native image

description: Build a native container image with bootBuildImage.

inputs:
  architecture:
    description: Target architecture (amd64 or arm64)
    required: true
  project:
    description: Gradle project to build (e.g. grpc, importer)
    required: true

runs:
  using: composite
  steps:
    - name: Get version
      shell: bash
      run: echo "VERSION=$(grep -oP 'version=\K.+' gradle.properties)" >> $GITHUB_ENV

    - name: Install JDK
      uses: actions/setup-java@dd06d9cba3e5552c54d9f8ea23572deb30010f7c # v6.0.0
      with:
        java-version-file: .sdkmanrc
        verify-signature: true

    - name: Setup Gradle
      uses: gradle/actions/setup-gradle@9c971963bec38e04b3d30dcc455b5382be2fdbfb # v4

    - name: Build
      shell: bash
      run: ./gradlew :${{ inputs.project }}:bootBuildImage -PimagePlatform=linux/${{ inputs.architecture }}
