apiVersion: notification.toolkit.fluxcd.io/v1beta3
kind: Alert
metadata:
  name: github
  namespace: flux-system
spec:
  eventMetadata:
    summary: "Pre-prod cluster"
  eventSeverity: info
  eventSources:
    - kind: Kustomization
      name: '*'
      namespace: flux-system
  providerRef:
    name: github

