---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: slack
  namespace: flux-system
spec:
  encryptedData:
    address: AgBOBf+0YVtOmbB0126pRwxAt9iCejZ9poIlmHIcQs7Ct+u3mIzLXGLsDGHGyzzTTIqDf7kBOWf4uwzJXeJ6W+2BSx+x1uljDIYpiBHYfYXdtFj+KcfIzjorVR0oKx7RsFYBvH+bYHWuzwsn6C13AgVXIhtTAkPp+4VAQKUS8mW6nyt6PTMmPiewxaO0xMk64RH2wEqjTxa8WDTDvKaVUVbaDMJhKU8gZkWptFY9ISzuhyeWT/PqOWyMbS/juo/S/6Ibmsy2FIS8BLJ2q8gochnJS0SUUSsj//hbDfHr3OAhj3IwfFp09D+YrcEyvJ6aPbeHybAnCeFpGInSvB7pKUQ6m29JXtuxZS91rPrm4jvhffnOwObDdGTOMQWvCHSifrajNfD1RV5swgTq80MC65mYLFY1xAPuH6DOqWA6VAryO3iMwLdiNLQpNd6teI1WymWreWA5c/YAenMceacB/BG7c2rQj7iT1RdxDUh/jZQUYybr/mcWjjkY5v6tXbf/5oNZt0C9QSe5Ap0VtlcDc/lPpI6KNjkmUUBiiDzDgfDVEXQxJ5KOThcy3BmqIaG5v2WdhWZ69DB5yE+P66aZxWLd2n2KSoG89QlaE/0Jtgi9/CrsqTNtsv+9C302rot0HN46ZvaTPe4JtrUt3ushrcgmdiNzuNgFNhRdXfA4sSgw7xBxmQcSXR+FCzVHw8mnvQewj+Zrw2n7t+pnYzpitI9klK34VAJXxUrF/K8lvfRJOHKRdeblqw==
    token: AgCT1D9QIAwsJNWP/hl0B4p6CnyWQXugnvnPYjlWVPRtqxcMpH/WUvMyrFJjYs6bWuE8L1SmVGes06wk4KztA13HV4aoVfPnLMTrv+co0LLd+qXrMYO5Oa0+GT8VMzU+0AHUVRITfmGN4QlfZkpgzsHWaPfvlN6XAm/ucBhygFft3WEp7oxrGypDP1fVX79/i/1U6Fy1WJheqSjtI31cjOxNaXfXP9xW4pcTxyJ2WR8O8Ymju9JiZW22MchFS27Lxxd/QjUfvtf2YzF+GtF634HqqTH/sq8Sq4/hZaoGKOmTiwD9UiCn+1coTUQAmxNvyrBfWkw/6vqd26fOzNP/1JjvpRfqi56PNbsfe3Rh+GKs7RjCFwFmmAolBwXicQZ7bsFYBU2R3E7hCebHQeXjXAubz15VGOj81eOiSQXZfjRtMEwu/Rl22u1NyEypQEzHemcSPNbyvKcteCEtdMgnZPnV39H1f/tJGGR9Da2llmLGLifvZP8RFlK061K29PwKBPcq2FgtnvVSNbXzXkjzIZQZ1iV6EIMQviWdtNFj77P7UBHAqzNBp19rXy+VNJD8FKLHrTkIDgWkEAbvjlypjoXFqbzIZrEvWxtdLNbhOvKYOTFHlsZqDNX4RBPinjuSB43lf9w9xTHNEKyGBGQcTpmkY8V+voR4URs1kYkCZ0Ms9fZ2wlY+jvgvyRbRjAOeIDGclsLmkuUp+u3KpseweB3znVjG19lxqAdayIM49/se05CUjAYD9jDVO2ogrDmIlHMLEwJLduJ7i6o=
  template:
    metadata:
      name: slack
      namespace: flux-system
    type: Opaque
