---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: grafana-cloud
  namespace: common
spec:
  encryptedData:
    password: AgCwc/RVsupwcXEsBtAmzP2nxRwLx7fnNFHAn7v5ZEwkbmGjrzSx8eiEwoDwDL0JXrHvDA4MkCnxf3WgtCAqgAnTJ6PcQT1PtFIIQXoDlU46TkTKUApNCl8oi0Q3gDxmHb+YOTN/NetipEkKVuqo75H4BzTFd/TUC6bu6kuN826FO27s9ReEX4ncmIYjLIdV555nEiegk781Jd96TQJkNE6Q12goDSoARrj7JrCBaed27bijayYQxu89GkpRXVkytUSYSmO8WA9Dyb4muyp6VJDHmWD2tez7IsbfByvSEX2jIm9w2/xUQof8s+go/xw8BIocqquuo64WUUxZ1pxG1yJvY8RQ03lG7a0CchN2CB3aSOT40S6hmGegLBjQGf8j0E0BFxYar6T8HL56NF2aVTKvuN1cLxId1opFcaOpTWsVePPNsl6YE6QxeVGKEslfp9OIx1pyKfotugTvEsVCyW6LYBdwoedbLAt2LoJNLtgSq7FtJv3MOYYGisR3lDiTGOXrhdHlIkQyYjke0jQ3MNGYf2aosBWvJb3iVmsKypoyIZBASp3BX20G8mCoXVXNhw8PJjD8CKgh0BC0PXHW9S4iD3OE9eN/D3WJ5pSkMe0R1K16XccMlRmle6cvH+UKYdUevjolv4qLbKdkzVfiAcmEM5sRDbRZobmfv2kMLCpBNdCo/G3SPH0tcwqR+h6i0EkHmX6CSg88qUJZSUpVEXR7IGXWiVJ2Maau6h4v3UAUSBsPAtVy4757bXY9yB4rPUYYXSvmTWj40GFCuv24rmsAG1JBWJbj8UeFW4+a07vvMw3Ltl/mHaDOIwKIKlNbhnMvyJi05rgMTEwjwPjFcnrd/AKKRA==
    username: AgBiqAvTaKM94X5pgWLje156nqGCp+uv0ItDBUVQuI8OHGzceFrMjYpK3YbyMVoIu5JJsu6huL6NvNM308TExUPIkYB/+HB5OIxf07oBkQ3yod2uN06IXg+qvdQbwl6KT5ruMTdaAII0azBLs/XE9CjK38o3Ux9DAZw/IeDE9CFPvPpzab/jdv8kHznN8HqKE04HkoqiKty69uvWNXgv7GveP2le4AWj/BENB5q/YT2YpMQ8qL0uCVo0JgffACCqWBJmhNUkRQGumuGfczPSF2uvNV0bSfog3Y34i53lZUOwbUkGADyrAhEX8ztQPg9DMVv/+8ANr1goDm09/TNy0p19VI7ZsJgR8dZ2FREI1t/sdxvhMXTFz2p6f271+rwe9f7josifPE+sZwD+ONxfy2GAIY8zxme4eBKNiF/QwpQDJws31grQjtK3Rly6kHPobGihS7SRJ7vuK4DAMrKHI0qq9P3ymdwi9vr9p4TU5f5dOfOGUz6qXWft0ouY3iwjg/2BqyrQ4owI39aBXFfrO42/iRoAMa+83mH53Us43yypzYdVuOCuL4bjcbUMFQxs9qtHMSclPFzMghrjIjQyJ5b7J9/IaJ0uEt/bIfmM/CDmkCIeeRFfTZpj+TtU5cLe3Q39rHdPflOehdO1WqcLpTmmKUqheIGqmmnwk0iWGcnqH4Acua4rIumcW6mTpNr0ky8W3DLNb1c=
  template:
    metadata:
      name: grafana-cloud
      namespace: common
    type: Opaque
