# SPDX-License-Identifier: Apache-2.0

name: End-to-end Tests

on:
  pull_request:
    branches:
      - "main"
      - "release/**"
    paths:
      - ".github/workflows/acceptance.yaml"
      - "test/**"
  push:
    branches:
      - "main"
      - "release/**"
  workflow_dispatch:
    inputs:
      branch:
        description: "Branch"
        required: true
        type: string

permissions:
  contents: read
  packages: read
  pull-requests: read

defaults:
  run:
    shell: bash

env:
  LC_ALL: C.UTF-8

jobs:
  acceptance:
    name: acceptance (${{ matrix.stream-type }})
    runs-on: hiero-mirror-node-linux-large
    timeout-minutes: 50
    strategy:
      fail-fast: false
      matrix:
        stream-type:
          - RECORD
          - BLOCK
    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@bf7454d06d71f1098171f2acdf0cd4708d7b5920 # v2.20.0
        with:
          egress-policy: audit

      - name: Checkout
        uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
        with:
          ref: ${{ github.event_name == 'workflow_dispatch' && github.event.inputs.branch || '' }}

      - name: Login to Docker Hub
        uses: step-security/docker-login-action@164e21d7e52229904128e2f946001cb88278c33d # v4.2.0
        if: vars.DOCKERHUB_USERNAME != '' && (github.event_name != 'pull_request' || github.event.pull_request.head.repo.full_name == github.repository)
        with:
          username: ${{ vars.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Run end-to-end tests
        uses: ./.github/actions/run-e2e
        with:
          build-changed-modules-only: "true"
          image-source: jvm
          stream-type: ${{ matrix.stream-type }}

      - name: Run k6 tests
        if: matrix.stream-type != 'BLOCK'
        env:
          BASE_URL: "http://127.0.0.1:38081"
          DEFAULT_DURATION: "3s"
          DEFAULT_GRACEFUL_STOP: "1s"
          DEFAULT_VUS: 2
          RUN_OPCODE_TESTS: "true"
        uses: ./.github/actions/k6
