# SPDX-License-Identifier: Apache-2.0

name: "Non-Zero Realm"
on:
  schedule:
    - cron: "0 0 * * *" # Daily at midnight
  workflow_dispatch:
    inputs:
      branch:
        description: "Branch"
        required: true
        type: string

defaults:
  run:
    shell: bash

permissions:
  contents: read

env:
  LC_ALL: C.UTF-8
  CGO_ENABLED: 1

jobs:
  build:
    name: Build
    env:
      HIERO_MIRROR_COMMON_REALM: 127
      HIERO_MIRROR_COMMON_SHARD: 113
    runs-on: hiero-mirror-node-linux-large
    strategy:
      fail-fast: false
      matrix:
        project:
          - common
          - graphql
          - grpc
          - importer
          - monitor
          - rest
          - rest-java
          - rosetta
          - web3
    timeout-minutes: 40 # increase it from 20 minutes since some jobs often run longer on self-hosted runners
    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@05e31511f85b41b11d1cf0ef85d0992719546e2c # v2.21.0
        with:
          egress-policy: audit

      - name: Checkout Code
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          ref: ${{ github.event_name == 'workflow_dispatch' && github.event.inputs.branch || github.ref }}

      - name: Install JDK
        uses: actions/setup-java@dd06d9cba3e5552c54d9f8ea23572deb30010f7c # v6.0.0
        with:
          java-version-file: .sdkmanrc
          verify-signature: true

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@9c971963bec38e04b3d30dcc455b5382be2fdbfb # v4

      - name: Execute Gradle
        run: ./gradlew :${{matrix.project}}:build
